export {
  DEFAULT_FIXTURE,
  FIXTURE_COPY,
  POMODORO_PERMISSIONS,
  POMODORO_SETTINGS,
  fixtureDeclarativePanelContent,
  fixtureInstalledPlugins,
  fixturePomodoroStructuredContent,
  fixtureStorePlugins,
  readFixture,
  type Phase7FixtureState,
  type Phase7SceneId,
  type PluginLoadMode,
  type StoreMode,
} from "./mocks/read-fixture";
