/**
 * Phase 6 Wave 4b AI transport surface.
 *
 * Transport/state only — no React context, routing, or view mounting.
 */

export { createAiOperationId, resolveOperationId, RetainedOperationId } from "./operation-id";

export {
  AiSseDecoder,
  AiRunSseReducer,
  consumeAiRunSseStream,
  createVisibleTextFrameBatcher,
  type AiRunStreamHandlers,
  type DecodedSseFrame,
} from "./sse";

export {
  listAiProviders,
  discoverAiProviderModels,
  getAiConfig,
  putAiConfig,
  deleteAiConfig,
  putAiCredential,
  deleteAiCredential,
  listAiSessions,
  createAiSession,
  getAiSession,
  updateAiSession,
  deleteAiSession,
  clearAiSession,
  listAiMessages,
  getAiMessage,
  createAiResponse,
  createAiDailyBriefing,
  editAiResponse,
  retryAiResponse,
  regenerateAiResponse,
  cancelAiRun,
  listAiMemories,
  createAiMemory,
  getAiMemory,
  updateAiMemory,
  deleteAiMemory,
  getAiApproval,
  approveAiApproval,
  rejectAiApproval,
  sanitizeTransportError,
  type AiTransportOptions,
  type AiStreamTransportOptions,
  type AiStreamResult,
} from "./transport";

export {
  AiSseError,
  AI_SSE_ENVELOPE_VERSION,
  AI_SSE_MAX_FRAME_BYTES,
  AI_SSE_MAX_BUFFER_BYTES,
  AI_ASSISTANT_TEXT_BYTES_MAX,
  AI_TOOL_ARGUMENTS_BYTES_MAX,
  AI_TOOL_RESULT_BYTES_MAX,
  AI_TOOL_EVENT_TRANSCRIPT_BYTES_MAX,
  AI_DIAGNOSTIC_STRING_BYTES_MAX,
  AI_RUN_EVENT_TYPES,
  createInitialAiRunStreamState,
  type AiSseErrorCode,
  type AiRunEventTypeName,
  type AiRunStreamState,
  type AiRunTerminalView,
  type AiRunUsageView,
  type AiToolProposalView,
  type AiToolDecisionView,
  type AiToolResultView,
  type AiConfigInput,
  type AiConfigPutRequest,
  type AiConfigResponse,
  type AiCredentialTargetDto,
  type PutAiCredentialRequest,
  type AiProviderPresetDto,
  type AiProviderRegistryResponse,
  type ModelDiscoveryResponse,
  type AiSessionDto,
  type AiSessionListResponse,
  type AiSessionMutationResponse,
  type CreateAiSessionHttpRequest,
  type PatchAiSessionRequest,
  type AiMessageDto,
  type AiMessageListResponse,
  type CreateAiResponseRequest,
  type EditAiResponseRequest,
  type CancelAiRunResponse,
  type AiMemoryDto,
  type AiMemoryListResponse,
  type AiMemoryMutationResponse,
  type CreateAiMemoryHttpRequest,
  type PatchAiMemoryRequest,
  type AiApprovalResponse,
  type AiApprovalDecisionRequest,
  type AiContextMetadata,
  type ListAiSessionsParams,
  type ListAiMemoriesParams,
  type ListAiMessagesParams,
} from "./types";
