// @generated by `cargo run -p junban-plugin-sdk --features codegen --bin junban-plugin-body-codegen`; do not edit.
#![allow(clippy::all)]

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Visitor};

pub const GENERATED_WIT_SHA256: &str =
    "5705801973219a0e6981693653f2caefdf1090345b65494750c8d8a9bf4b15f4";
pub const BYTE_LIST_BYTES_MAX: usize = 4 * 1024 * 1024;

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ByteList(Vec<u8>);

impl ByteList {
    pub fn new(bytes: Vec<u8>) -> Result<Self, crate::SdkError> {
        if bytes.len() > BYTE_LIST_BYTES_MAX {
            return Err(crate::SdkError::Protocol {
                field: "byte list length",
            });
        }
        Ok(Self(bytes))
    }

    #[must_use]
    pub fn as_slice(&self) -> &[u8] {
        &self.0
    }

    #[must_use]
    pub fn into_vec(self) -> Vec<u8> {
        self.0
    }
}

impl Serialize for ByteList {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        if self.0.len() > BYTE_LIST_BYTES_MAX {
            return Err(serde::ser::Error::custom(
                "byte list exceeds private body bound",
            ));
        }
        serializer.serialize_str(&URL_SAFE_NO_PAD.encode(&self.0))
    }
}

impl<'de> Deserialize<'de> for ByteList {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct ByteListVisitor;

        impl Visitor<'_> for ByteListVisitor {
            type Value = ByteList;

            fn expecting(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                formatter.write_str("strict unpadded base64url bytes")
            }

            fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
            where
                E: serde::de::Error,
            {
                let encoded_max = BYTE_LIST_BYTES_MAX.saturating_mul(4).div_ceil(3);
                if value.len() > encoded_max {
                    return Err(E::custom("byte list exceeds private body bound"));
                }
                let bytes = URL_SAFE_NO_PAD
                    .decode(value)
                    .map_err(|_| E::custom("invalid base64url byte list"))?;
                if bytes.len() > BYTE_LIST_BYTES_MAX || URL_SAFE_NO_PAD.encode(&bytes) != value {
                    return Err(E::custom("noncanonical base64url byte list"));
                }
                Ok(ByteList(bytes))
            }
        }

        deserializer.deserialize_str(ByteListVisitor)
    }
}

pub(crate) fn deserialize_present_option<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer)
}

pub type Id = String;

pub type Date = String;

pub type CivilTime = String;

pub type TimeZoneName = String;

pub type Timestamp = String;

pub type OperationId = String;

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum Priority {
    #[serde(rename = "p1")]
    P1,
    #[serde(rename = "p2")]
    P2,
    #[serde(rename = "p3")]
    P3,
    #[serde(rename = "p4")]
    P4,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum TaskStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ProjectView {
    #[serde(rename = "list")]
    List,
    #[serde(rename = "board")]
    Board,
    #[serde(rename = "calendar")]
    Calendar,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum LogLevel {
    #[serde(rename = "debug")]
    Debug,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warn")]
    Warn,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ErrorCode {
    #[serde(rename = "invalid-input")]
    InvalidInput,
    #[serde(rename = "not-found")]
    NotFound,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "cursor-stale")]
    CursorStale,
    #[serde(rename = "permission-denied")]
    PermissionDenied,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "rate-limited")]
    RateLimited,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "internal")]
    Internal,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HostError {
    #[serde(rename = "code")]
    pub code: ErrorCode,
    #[serde(rename = "field")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub field: Option<String>,
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PluginError {
    #[serde(rename = "code")]
    pub code: ErrorCode,
    #[serde(rename = "field")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub field: Option<String>,
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum ScalarValue {
    #[serde(rename = "string-value")]
    StringValue(String),
    #[serde(rename = "integer-value")]
    IntegerValue(i64),
    #[serde(rename = "boolean-value")]
    BooleanValue(bool),
    #[serde(rename = "date-value")]
    DateValue(Date),
    #[serde(rename = "timestamp-value")]
    TimestampValue(Timestamp),
    #[serde(rename = "task-id")]
    TaskId(Id),
    #[serde(rename = "project-id")]
    ProjectId(Id),
    #[serde(rename = "tag-id")]
    TagId(Id),
    #[serde(rename = "plugin-id")]
    PluginId(Id),
    #[serde(rename = "option-id")]
    OptionId(Id),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum DataValue {
    #[serde(rename = "scalar")]
    Scalar(ScalarValue),
    #[serde(rename = "string-list")]
    StringList(Vec<String>),
    #[serde(rename = "integer-list")]
    IntegerList(Vec<i64>),
    #[serde(rename = "boolean-list")]
    BooleanList(Vec<bool>),
    #[serde(rename = "date-list")]
    DateList(Vec<Date>),
    #[serde(rename = "timestamp-list")]
    TimestampList(Vec<Timestamp>),
    #[serde(rename = "task-id-list")]
    TaskIdList(Vec<Id>),
    #[serde(rename = "project-id-list")]
    ProjectIdList(Vec<Id>),
    #[serde(rename = "tag-id-list")]
    TagIdList(Vec<Id>),
    #[serde(rename = "plugin-id-list")]
    PluginIdList(Vec<Id>),
    #[serde(rename = "option-id-list")]
    OptionIdList(Vec<Id>),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NamedValue {
    #[serde(rename = "name")]
    pub name: Id,
    #[serde(rename = "value")]
    pub value: DataValue,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ScalarNamedValue {
    #[serde(rename = "name")]
    pub name: Id,
    #[serde(rename = "value")]
    pub value: ScalarValue,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct InvocationContext {
    #[serde(rename = "plugin-id")]
    pub plugin_id: Id,
    #[serde(rename = "package-generation")]
    pub package_generation: u64,
    #[serde(rename = "activation-epoch")]
    pub activation_epoch: u64,
    #[serde(rename = "host-session-id")]
    pub host_session_id: Id,
    #[serde(rename = "invocation-id")]
    pub invocation_id: OperationId,
    #[serde(rename = "entry-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub entry_id: Option<Id>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LocalDueTime {
    #[serde(rename = "time")]
    pub time: CivilTime,
    #[serde(rename = "time-zone")]
    pub time_zone: TimeZoneName,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TaskQuery {
    #[serde(rename = "task-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub task_id: Option<Id>,
    #[serde(rename = "project-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub project_id: Option<Id>,
    #[serde(rename = "section-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub section_id: Option<Id>,
    #[serde(rename = "parent-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub parent_id: Option<Id>,
    #[serde(rename = "tag-ids")]
    pub tag_ids: Vec<Id>,
    #[serde(rename = "statuses")]
    pub statuses: Vec<TaskStatus>,
    #[serde(rename = "priorities")]
    pub priorities: Vec<Priority>,
    #[serde(rename = "due-from")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub due_from: Option<Date>,
    #[serde(rename = "due-before")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub due_before: Option<Date>,
    #[serde(rename = "search")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub search: Option<String>,
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    pub limit: u16,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TaskView {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: TaskStatus,
    #[serde(rename = "priority")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub priority: Option<Priority>,
    #[serde(rename = "due-date")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub due_date: Option<Date>,
    #[serde(rename = "due-time")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub due_time: Option<LocalDueTime>,
    #[serde(rename = "deadline")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub deadline: Option<Timestamp>,
    #[serde(rename = "someday")]
    pub someday: bool,
    #[serde(rename = "estimated-minutes")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub estimated_minutes: Option<u32>,
    #[serde(rename = "actual-minutes")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub actual_minutes: Option<u32>,
    #[serde(rename = "dread")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub dread: Option<u8>,
    #[serde(rename = "project-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub project_id: Option<Id>,
    #[serde(rename = "section-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub section_id: Option<Id>,
    #[serde(rename = "parent-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub parent_id: Option<Id>,
    #[serde(rename = "tag-ids")]
    pub tag_ids: Vec<Id>,
    #[serde(rename = "sort-order")]
    pub sort_order: i64,
    #[serde(rename = "recurrence-rule")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub recurrence_rule: Option<String>,
    #[serde(rename = "remind-at")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub remind_at: Option<Timestamp>,
    #[serde(rename = "recurrence-anchor-day")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub recurrence_anchor_day: Option<u8>,
    #[serde(rename = "created-at")]
    pub created_at: Timestamp,
    #[serde(rename = "updated-at")]
    pub updated_at: Timestamp,
    #[serde(rename = "revision")]
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TaskPage {
    #[serde(rename = "items")]
    pub items: Vec<TaskView>,
    #[serde(rename = "next-cursor")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub next_cursor: Option<String>,
    #[serde(rename = "revision")]
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CatalogQuery {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    pub limit: u16,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ProjectViewRecord {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "icon")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub icon: Option<String>,
    #[serde(rename = "parent-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub parent_id: Option<Id>,
    #[serde(rename = "favorite")]
    pub favorite: bool,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "view")]
    pub view: ProjectView,
    #[serde(rename = "sort-order")]
    pub sort_order: i64,
    #[serde(rename = "created-at")]
    pub created_at: Timestamp,
    #[serde(rename = "updated-at")]
    pub updated_at: Timestamp,
    #[serde(rename = "revision")]
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ProjectPage {
    #[serde(rename = "items")]
    pub items: Vec<ProjectViewRecord>,
    #[serde(rename = "next-cursor")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub next_cursor: Option<String>,
    #[serde(rename = "revision")]
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TagView {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "created-at")]
    pub created_at: Timestamp,
    #[serde(rename = "updated-at")]
    pub updated_at: Timestamp,
    #[serde(rename = "revision")]
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TagPage {
    #[serde(rename = "items")]
    pub items: Vec<TagView>,
    #[serde(rename = "next-cursor")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub next_cursor: Option<String>,
    #[serde(rename = "revision")]
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SectionView {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "project-id")]
    pub project_id: Id,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "collapsed")]
    pub collapsed: bool,
    #[serde(rename = "sort-order")]
    pub sort_order: i64,
    #[serde(rename = "created-at")]
    pub created_at: Timestamp,
    #[serde(rename = "updated-at")]
    pub updated_at: Timestamp,
    #[serde(rename = "revision")]
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum StringChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "set")]
    Set(String),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum BoolChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "set")]
    Set(bool),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum S64Change {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "set")]
    Set(i64),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum ProjectViewChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "set")]
    Set(ProjectView),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalStringChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(String),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalIdChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(Id),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalDateChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(Date),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalTimestampChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(Timestamp),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalLocalDueTimeChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(LocalDueTime),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalU32Change {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(u32),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalU8Change {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(u8),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum OptionalPriorityChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(Priority),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum IdListChange {
    #[serde(rename = "unchanged")]
    Unchanged(()),
    #[serde(rename = "replace")]
    Replace(Vec<Id>),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TaskDraft {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "priority")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub priority: Option<Priority>,
    #[serde(rename = "due-date")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub due_date: Option<Date>,
    #[serde(rename = "due-time")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub due_time: Option<LocalDueTime>,
    #[serde(rename = "deadline")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub deadline: Option<Timestamp>,
    #[serde(rename = "someday")]
    pub someday: bool,
    #[serde(rename = "estimated-minutes")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub estimated_minutes: Option<u32>,
    #[serde(rename = "actual-minutes")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub actual_minutes: Option<u32>,
    #[serde(rename = "dread")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub dread: Option<u8>,
    #[serde(rename = "project-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub project_id: Option<Id>,
    #[serde(rename = "section-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub section_id: Option<Id>,
    #[serde(rename = "parent-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub parent_id: Option<Id>,
    #[serde(rename = "tag-ids")]
    pub tag_ids: Vec<Id>,
    #[serde(rename = "sort-order")]
    pub sort_order: i64,
    #[serde(rename = "recurrence-rule")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub recurrence_rule: Option<String>,
    #[serde(rename = "remind-at")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub remind_at: Option<Timestamp>,
    #[serde(rename = "recurrence-anchor-day")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub recurrence_anchor_day: Option<u8>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TaskPatch {
    #[serde(rename = "title")]
    pub title: StringChange,
    #[serde(rename = "description")]
    pub description: StringChange,
    #[serde(rename = "priority")]
    pub priority: OptionalPriorityChange,
    #[serde(rename = "due-date")]
    pub due_date: OptionalDateChange,
    #[serde(rename = "due-time")]
    pub due_time: OptionalLocalDueTimeChange,
    #[serde(rename = "deadline")]
    pub deadline: OptionalTimestampChange,
    #[serde(rename = "someday")]
    pub someday: BoolChange,
    #[serde(rename = "estimated-minutes")]
    pub estimated_minutes: OptionalU32Change,
    #[serde(rename = "actual-minutes")]
    pub actual_minutes: OptionalU32Change,
    #[serde(rename = "dread")]
    pub dread: OptionalU8Change,
    #[serde(rename = "project-id")]
    pub project_id: OptionalIdChange,
    #[serde(rename = "section-id")]
    pub section_id: OptionalIdChange,
    #[serde(rename = "parent-id")]
    pub parent_id: OptionalIdChange,
    #[serde(rename = "tag-ids")]
    pub tag_ids: IdListChange,
    #[serde(rename = "sort-order")]
    pub sort_order: S64Change,
    #[serde(rename = "recurrence-rule")]
    pub recurrence_rule: OptionalStringChange,
    #[serde(rename = "remind-at")]
    pub remind_at: OptionalTimestampChange,
    #[serde(rename = "recurrence-anchor-day")]
    pub recurrence_anchor_day: OptionalU8Change,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PatchTask {
    #[serde(rename = "task-id")]
    pub task_id: Id,
    #[serde(rename = "patch")]
    pub patch: TaskPatch,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BulkMove {
    #[serde(rename = "project-id")]
    pub project_id: OptionalIdChange,
    #[serde(rename = "section-id")]
    pub section_id: OptionalIdChange,
    #[serde(rename = "parent-id")]
    pub parent_id: OptionalIdChange,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BulkTag {
    #[serde(rename = "add")]
    pub add: Vec<Id>,
    #[serde(rename = "remove")]
    pub remove: Vec<Id>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BulkSchedule {
    #[serde(rename = "due-date")]
    pub due_date: OptionalDateChange,
    #[serde(rename = "due-time")]
    pub due_time: OptionalLocalDueTimeChange,
    #[serde(rename = "deadline")]
    pub deadline: OptionalTimestampChange,
    #[serde(rename = "someday")]
    pub someday: BoolChange,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum BulkPriority {
    #[serde(rename = "clear")]
    Clear(()),
    #[serde(rename = "set")]
    Set(Priority),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum BulkAction {
    #[serde(rename = "complete")]
    Complete(()),
    #[serde(rename = "uncomplete")]
    Uncomplete(()),
    #[serde(rename = "cancel")]
    Cancel(()),
    #[serde(rename = "reopen")]
    Reopen(()),
    #[serde(rename = "delete")]
    Delete(()),
    #[serde(rename = "move")]
    Move(BulkMove),
    #[serde(rename = "tag")]
    Tag(BulkTag),
    #[serde(rename = "schedule")]
    Schedule(BulkSchedule),
    #[serde(rename = "priority")]
    Priority(BulkPriority),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BulkTasks {
    #[serde(rename = "task-ids")]
    pub task_ids: Vec<Id>,
    #[serde(rename = "action")]
    pub action: BulkAction,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ProjectDraft {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "icon")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub icon: Option<String>,
    #[serde(rename = "parent-id")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub parent_id: Option<Id>,
    #[serde(rename = "favorite")]
    pub favorite: bool,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "view")]
    pub view: ProjectView,
    #[serde(rename = "sort-order")]
    pub sort_order: i64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ProjectPatch {
    #[serde(rename = "name")]
    pub name: StringChange,
    #[serde(rename = "color")]
    pub color: StringChange,
    #[serde(rename = "icon")]
    pub icon: OptionalStringChange,
    #[serde(rename = "parent-id")]
    pub parent_id: OptionalIdChange,
    #[serde(rename = "favorite")]
    pub favorite: BoolChange,
    #[serde(rename = "archived")]
    pub archived: BoolChange,
    #[serde(rename = "view")]
    pub view: ProjectViewChange,
    #[serde(rename = "sort-order")]
    pub sort_order: S64Change,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PatchProject {
    #[serde(rename = "project-id")]
    pub project_id: Id,
    #[serde(rename = "patch")]
    pub patch: ProjectPatch,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TagDraft {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "color")]
    pub color: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TagPatch {
    #[serde(rename = "name")]
    pub name: StringChange,
    #[serde(rename = "color")]
    pub color: StringChange,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PatchTag {
    #[serde(rename = "tag-id")]
    pub tag_id: Id,
    #[serde(rename = "patch")]
    pub patch: TagPatch,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum DomainMutation {
    #[serde(rename = "create-task")]
    CreateTask(TaskDraft),
    #[serde(rename = "patch-task")]
    PatchTask(PatchTask),
    #[serde(rename = "complete-task")]
    CompleteTask(Id),
    #[serde(rename = "uncomplete-task")]
    UncompleteTask(Id),
    #[serde(rename = "cancel-task")]
    CancelTask(Id),
    #[serde(rename = "reopen-task")]
    ReopenTask(Id),
    #[serde(rename = "delete-task")]
    DeleteTask(Id),
    #[serde(rename = "bulk-tasks")]
    BulkTasks(BulkTasks),
    #[serde(rename = "create-project")]
    CreateProject(ProjectDraft),
    #[serde(rename = "patch-project")]
    PatchProject(PatchProject),
    #[serde(rename = "delete-project")]
    DeleteProject(Id),
    #[serde(rename = "create-tag")]
    CreateTag(TagDraft),
    #[serde(rename = "patch-tag")]
    PatchTag(PatchTag),
    #[serde(rename = "delete-tag")]
    DeleteTag(Id),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct KvSet {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: ByteList,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum KvOperation {
    #[serde(rename = "set")]
    Set(KvSet),
    #[serde(rename = "delete")]
    Delete(String),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct KvPatch {
    #[serde(rename = "operations")]
    pub operations: Vec<KvOperation>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum PluginEffect {
    #[serde(rename = "domain-mutation")]
    DomainMutation(DomainMutation),
    #[serde(rename = "kv-patch")]
    KvPatch(KvPatch),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PluginOutcome {
    #[serde(rename = "effect")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub effect: Option<PluginEffect>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CommandCall {
    #[serde(rename = "command-id")]
    pub command_id: Id,
    #[serde(rename = "values")]
    pub values: Vec<NamedValue>,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum EventKind {
    #[serde(rename = "task-created")]
    TaskCreated,
    #[serde(rename = "task-updated")]
    TaskUpdated,
    #[serde(rename = "task-completed")]
    TaskCompleted,
    #[serde(rename = "task-uncompleted")]
    TaskUncompleted,
    #[serde(rename = "task-cancelled")]
    TaskCancelled,
    #[serde(rename = "task-reopened")]
    TaskReopened,
    #[serde(rename = "task-deleted")]
    TaskDeleted,
    #[serde(rename = "project-created")]
    ProjectCreated,
    #[serde(rename = "project-updated")]
    ProjectUpdated,
    #[serde(rename = "project-deleted")]
    ProjectDeleted,
    #[serde(rename = "tag-created")]
    TagCreated,
    #[serde(rename = "tag-updated")]
    TagUpdated,
    #[serde(rename = "tag-deleted")]
    TagDeleted,
    #[serde(rename = "section-created")]
    SectionCreated,
    #[serde(rename = "section-updated")]
    SectionUpdated,
    #[serde(rename = "section-deleted")]
    SectionDeleted,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum EventSubject {
    #[serde(rename = "task")]
    Task(TaskView),
    #[serde(rename = "project")]
    Project(ProjectViewRecord),
    #[serde(rename = "tag")]
    Tag(TagView),
    #[serde(rename = "section")]
    Section(SectionView),
    #[serde(rename = "deleted-task")]
    DeletedTask(Id),
    #[serde(rename = "deleted-project")]
    DeletedProject(Id),
    #[serde(rename = "deleted-tag")]
    DeletedTag(Id),
    #[serde(rename = "deleted-section")]
    DeletedSection(Id),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EventEnvelope {
    #[serde(rename = "event-epoch")]
    pub event_epoch: Id,
    #[serde(rename = "revision")]
    pub revision: u64,
    #[serde(rename = "kind")]
    pub kind: EventKind,
    #[serde(rename = "subject")]
    pub subject: EventSubject,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum UiTone {
    #[serde(rename = "neutral")]
    Neutral,
    #[serde(rename = "accent")]
    Accent,
    #[serde(rename = "positive")]
    Positive,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "danger")]
    Danger,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum UiSize {
    #[serde(rename = "small")]
    Small,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "large")]
    Large,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum UiAlign {
    #[serde(rename = "start")]
    Start,
    #[serde(rename = "center")]
    Center,
    #[serde(rename = "end")]
    End,
    #[serde(rename = "stretch")]
    Stretch,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LayoutProps {
    #[serde(rename = "gap")]
    pub gap: u8,
    #[serde(rename = "align")]
    pub align: UiAlign,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TextProps {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "tone")]
    pub tone: UiTone,
    #[serde(rename = "size")]
    pub size: UiSize,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct MetricProps {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "tone")]
    pub tone: UiTone,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ProgressProps {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "value")]
    pub value: u16,
    #[serde(rename = "maximum")]
    pub maximum: u16,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ButtonProps {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "action-id")]
    pub action_id: Id,
    #[serde(rename = "tone")]
    pub tone: UiTone,
    #[serde(rename = "icon")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub icon: Option<Id>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct InputProps {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "action-id")]
    pub action_id: Id,
    #[serde(rename = "value")]
    pub value: ScalarValue,
    #[serde(rename = "options")]
    pub options: Vec<ScalarNamedValue>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TaskListProps {
    #[serde(rename = "task-ids")]
    pub task_ids: Vec<Id>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum UiContent {
    #[serde(rename = "stack")]
    Stack(LayoutProps),
    #[serde(rename = "row")]
    Row(LayoutProps),
    #[serde(rename = "heading")]
    Heading(TextProps),
    #[serde(rename = "text")]
    Text(TextProps),
    #[serde(rename = "badge")]
    Badge(TextProps),
    #[serde(rename = "metric")]
    Metric(MetricProps),
    #[serde(rename = "progress")]
    Progress(ProgressProps),
    #[serde(rename = "button")]
    Button(ButtonProps),
    #[serde(rename = "text-input")]
    TextInput(InputProps),
    #[serde(rename = "number-input")]
    NumberInput(InputProps),
    #[serde(rename = "select")]
    Select(InputProps),
    #[serde(rename = "toggle")]
    Toggle(InputProps),
    #[serde(rename = "task-list")]
    TaskList(TaskListProps),
    #[serde(rename = "task-ref")]
    TaskRef(Id),
    #[serde(rename = "divider")]
    Divider(()),
    #[serde(rename = "empty-state")]
    EmptyState(TextProps),
    #[serde(rename = "error-state")]
    ErrorState(TextProps),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct UiNode {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "parent-index")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub parent_index: Option<u16>,
    #[serde(rename = "content")]
    pub content: UiContent,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Surface {
    #[serde(rename = "surface-id")]
    pub surface_id: Id,
    #[serde(rename = "root-index")]
    pub root_index: u16,
    #[serde(rename = "nodes")]
    pub nodes: Vec<UiNode>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SurfaceRequest {
    #[serde(rename = "surface-id")]
    pub surface_id: Id,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SurfaceAction {
    #[serde(rename = "surface-id")]
    pub surface_id: Id,
    #[serde(rename = "action-id")]
    pub action_id: Id,
    #[serde(rename = "values")]
    pub values: Vec<ScalarNamedValue>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum SettingValue {
    #[serde(rename = "text")]
    Text(String),
    #[serde(rename = "integer")]
    Integer(i64),
    #[serde(rename = "boolean")]
    Boolean(bool),
    #[serde(rename = "option-id")]
    OptionId(Id),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NamedSetting {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "value")]
    pub value: SettingValue,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ValidationIssue {
    #[serde(rename = "setting-id")]
    pub setting_id: Id,
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SettingValues {
    #[serde(rename = "values")]
    pub values: Vec<NamedSetting>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ServiceCall {
    #[serde(rename = "plugin-id")]
    pub plugin_id: Id,
    #[serde(rename = "service-id")]
    pub service_id: Id,
    #[serde(rename = "values")]
    pub values: Vec<NamedValue>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ServiceData {
    #[serde(rename = "values")]
    pub values: Vec<NamedValue>,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ResourceKind {
    #[serde(rename = "task")]
    Task,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "tag")]
    Tag,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum SnapshotRecords {
    #[serde(rename = "tasks")]
    Tasks(Vec<TaskView>),
    #[serde(rename = "projects")]
    Projects(Vec<ProjectViewRecord>),
    #[serde(rename = "tags")]
    Tags(Vec<TagView>),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SnapshotPage {
    #[serde(rename = "session-id")]
    pub session_id: Id,
    #[serde(rename = "event-epoch")]
    pub event_epoch: Id,
    #[serde(rename = "head-revision")]
    pub head_revision: u64,
    #[serde(rename = "kind")]
    pub kind: ResourceKind,
    #[serde(rename = "page-index")]
    pub page_index: u32,
    #[serde(rename = "records")]
    pub records: SnapshotRecords,
    #[serde(rename = "final-snapshot-page")]
    pub final_snapshot_page: bool,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FlushStagedKv {
    #[serde(rename = "session-id")]
    pub session_id: Id,
    #[serde(rename = "request-index")]
    pub request_index: u8,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FinalizeResync {
    #[serde(rename = "session-id")]
    pub session_id: Id,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum ResyncPage {
    #[serde(rename = "snapshot")]
    Snapshot(SnapshotPage),
    #[serde(rename = "flush-staged-kv")]
    FlushStagedKv(FlushStagedKv),
    #[serde(rename = "finalize")]
    Finalize(FinalizeResync),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct KvSegment {
    #[serde(rename = "operations")]
    pub operations: Vec<KvOperation>,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum FlushState {
    #[serde(rename = "more")]
    More,
    #[serde(rename = "complete")]
    Complete,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum FinalKvChoice {
    #[serde(rename = "leave-kv")]
    LeaveKv,
    #[serde(rename = "replace-kv-with-staged-segments")]
    ReplaceKvWithStagedSegments,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SnapshotAck {
    #[serde(rename = "session-id")]
    pub session_id: Id,
    #[serde(rename = "page-index")]
    pub page_index: u32,
    #[serde(rename = "kind")]
    pub kind: ResourceKind,
    #[serde(rename = "segment")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub segment: Option<KvSegment>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FlushAck {
    #[serde(rename = "session-id")]
    pub session_id: Id,
    #[serde(rename = "request-index")]
    pub request_index: u8,
    #[serde(rename = "segment")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub segment: Option<KvSegment>,
    #[serde(rename = "state")]
    pub state: FlushState,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FinalizedResync {
    #[serde(rename = "session-id")]
    pub session_id: Id,
    #[serde(rename = "choice")]
    pub choice: FinalKvChoice,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum ResyncPageOutcome {
    #[serde(rename = "snapshot-ack")]
    SnapshotAck(SnapshotAck),
    #[serde(rename = "flush-ack")]
    FlushAck(FlushAck),
    #[serde(rename = "finalized")]
    Finalized(FinalizedResync),
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HttpMethod {
    #[serde(rename = "get")]
    Get,
    #[serde(rename = "post")]
    Post,
    #[serde(rename = "put")]
    Put,
    #[serde(rename = "patch")]
    Patch,
    #[serde(rename = "delete")]
    Delete,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HttpHeader {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HttpRequest {
    #[serde(rename = "method")]
    pub method: HttpMethod,
    #[serde(rename = "origin")]
    pub origin: String,
    #[serde(rename = "path-and-query")]
    pub path_and_query: String,
    #[serde(rename = "headers")]
    pub headers: Vec<HttpHeader>,
    #[serde(rename = "body")]
    pub body: ByteList,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HttpResponse {
    #[serde(rename = "status")]
    pub status: u16,
    #[serde(rename = "headers")]
    pub headers: Vec<HttpHeader>,
    #[serde(rename = "body")]
    pub body: ByteList,
    #[serde(rename = "truncated")]
    pub truncated: bool,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum HttpErrorCode {
    #[serde(rename = "invalid-request")]
    InvalidRequest,
    #[serde(rename = "invalid-response")]
    InvalidResponse,
    #[serde(rename = "permission-denied")]
    PermissionDenied,
    #[serde(rename = "dns-denied")]
    DnsDenied,
    #[serde(rename = "tls-failed")]
    TlsFailed,
    #[serde(rename = "connect-failed")]
    ConnectFailed,
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "delivery-ambiguous")]
    DeliveryAmbiguous,
    #[serde(rename = "unavailable")]
    Unavailable,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum DeliveryState {
    #[serde(rename = "not-sent")]
    NotSent,
    #[serde(rename = "may-have-been-sent")]
    MayHaveBeenSent,
    #[serde(rename = "response-received")]
    ResponseReceived,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HttpError {
    #[serde(rename = "code")]
    pub code: HttpErrorCode,
    #[serde(rename = "delivery")]
    pub delivery: DeliveryState,
    #[serde(rename = "retryable")]
    pub retryable: bool,
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LogField {
    #[serde(rename = "name")]
    pub name: Id,
    #[serde(rename = "value")]
    pub value: ScalarValue,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct KvEntry {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: ByteList,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct KvPage {
    #[serde(rename = "entries")]
    pub entries: Vec<KvEntry>,
    #[serde(rename = "next-cursor")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "tag", content = "val", deny_unknown_fields)]
pub enum WitResult<T, E> {
    #[serde(rename = "ok")]
    Ok(T),
    #[serde(rename = "err")]
    Err(E),
}

impl<T, E> WitResult<T, E> {
    pub fn into_result(self) -> std::result::Result<T, E> {
        match self {
            Self::Ok(value) => Ok(value),
            Self::Err(error) => Err(error),
        }
    }
}

pub type GuestActivateArgument = ();
pub type GuestActivateResult = WitResult<(), PluginError>;

pub type GuestDeactivateArgument = ();
pub type GuestDeactivateResult = WitResult<(), PluginError>;

pub type GuestInvokeCommandArgument = CommandCall;
pub type GuestInvokeCommandResult = WitResult<PluginOutcome, PluginError>;

pub type GuestHandleEventArgument = EventEnvelope;
pub type GuestHandleEventResult = WitResult<PluginOutcome, PluginError>;

pub type GuestRenderSurfaceArgument = SurfaceRequest;
pub type GuestRenderSurfaceResult = WitResult<Surface, PluginError>;

pub type GuestHandleSurfaceActionArgument = SurfaceAction;
pub type GuestHandleSurfaceActionResult = WitResult<PluginOutcome, PluginError>;

pub type GuestValidateSettingsArgument = SettingValues;
pub type GuestValidateSettingsResult = WitResult<Vec<ValidationIssue>, PluginError>;

pub type GuestResyncArgument = ResyncPage;
pub type GuestResyncResult = WitResult<ResyncPageOutcome, PluginError>;

pub type GuestCallServiceArgument = ServiceCall;
pub type GuestCallServiceResult = WitResult<ServiceData, PluginError>;

pub type HostTasksQueryTasksArguments = TaskQuery;
pub type HostTasksQueryTasksResult = WitResult<TaskPage, HostError>;

pub type HostProjectsQueryProjectsArguments = CatalogQuery;
pub type HostProjectsQueryProjectsResult = WitResult<ProjectPage, HostError>;

pub type HostTagsQueryTagsArguments = CatalogQuery;
pub type HostTagsQueryTagsResult = WitResult<TagPage, HostError>;

pub type HostSettingsGetSettingsArguments = ();
pub type HostSettingsGetSettingsResult = WitResult<Vec<NamedSetting>, HostError>;

pub type HostStorageGetKvArguments = Vec<String>;
pub type HostStorageGetKvResult = WitResult<Vec<KvEntry>, HostError>;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HostStorageListKvArguments {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "deserialize_present_option")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    pub limit: u8,
}
pub type HostStorageListKvResult = WitResult<KvPage, HostError>;

pub type HostClockWallNowArguments = ();
pub type HostClockWallNowResult = Timestamp;

pub type HostClockMonotonicMsArguments = ();
pub type HostClockMonotonicMsResult = u64;

pub type HostHttpRequestArguments = HttpRequest;
pub type HostHttpRequestResult = WitResult<HttpResponse, HttpError>;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HostLogLogArguments {
    #[serde(rename = "level")]
    pub level: LogLevel,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "fields")]
    pub fields: Vec<LogField>,
}
pub type HostLogLogResult = ();

pub type HostServicesCallServiceArguments = ServiceCall;
pub type HostServicesCallServiceResult = WitResult<ServiceData, HostError>;
