// @generated by junban-plugin-artifact registry include-table; do not edit.
pub(super) const BUNDLED_REGISTRY_PACKAGES: &[(&str, &[u8])] = &[
    (
        "sha256/14457dc76c42c23178ec56fa5e4fcb9fa27dd1996a795db70cf64adf07e48ee1.jbp",
        include_bytes!("../../../plugins/registry/sha256/14457dc76c42c23178ec56fa5e4fcb9fa27dd1996a795db70cf64adf07e48ee1.jbp"),
    ),
    (
        "sha256/69daf8a5346a7d9e213f8d4e49aaa11f12014ebfa1252082750e1597d1805085.jbp",
        include_bytes!("../../../plugins/registry/sha256/69daf8a5346a7d9e213f8d4e49aaa11f12014ebfa1252082750e1597d1805085.jbp"),
    ),
    (
        "sha256/829723f49e2ec911f93d40dfcc2664ee08f495f9e710d227434f07456e0d103b.jbp",
        include_bytes!("../../../plugins/registry/sha256/829723f49e2ec911f93d40dfcc2664ee08f495f9e710d227434f07456e0d103b.jbp"),
    ),
];
