// @generated by `cargo run -p junban-plugin-sdk --features codegen --bin junban-plugin-body-codegen`; do not edit.
#![allow(clippy::all, dead_code)]

#[rustfmt::skip]
mod generated {
use crate::bindings::junban::plugin::types as binding;
use junban_plugin_sdk::{SdkError, private_body_types as neutral};

const GENERATED_WIT_SHA256: &str = "5705801973219a0e6981693653f2caefdf1090345b65494750c8d8a9bf4b15f4";
type AdapterResult<T> = std::result::Result<T, SdkError>;

impl From<neutral::Priority> for binding::Priority {
    fn from(value: neutral::Priority) -> Self {
        match value {
            neutral::Priority::P1 => Self::P1,
            neutral::Priority::P2 => Self::P2,
            neutral::Priority::P3 => Self::P3,
            neutral::Priority::P4 => Self::P4,
        }
    }
}

impl TryFrom<binding::Priority> for neutral::Priority {
    type Error = SdkError;
    fn try_from(value: binding::Priority) -> AdapterResult<Self> {
        Ok(match value {
            binding::Priority::P1 => Self::P1,
            binding::Priority::P2 => Self::P2,
            binding::Priority::P3 => Self::P3,
            binding::Priority::P4 => Self::P4,
        })
    }
}

impl From<neutral::TaskStatus> for binding::TaskStatus {
    fn from(value: neutral::TaskStatus) -> Self {
        match value {
            neutral::TaskStatus::Pending => Self::Pending,
            neutral::TaskStatus::Completed => Self::Completed,
            neutral::TaskStatus::Cancelled => Self::Cancelled,
        }
    }
}

impl TryFrom<binding::TaskStatus> for neutral::TaskStatus {
    type Error = SdkError;
    fn try_from(value: binding::TaskStatus) -> AdapterResult<Self> {
        Ok(match value {
            binding::TaskStatus::Pending => Self::Pending,
            binding::TaskStatus::Completed => Self::Completed,
            binding::TaskStatus::Cancelled => Self::Cancelled,
        })
    }
}

impl From<neutral::ProjectView> for binding::ProjectView {
    fn from(value: neutral::ProjectView) -> Self {
        match value {
            neutral::ProjectView::List => Self::List,
            neutral::ProjectView::Board => Self::Board,
            neutral::ProjectView::Calendar => Self::Calendar,
        }
    }
}

impl TryFrom<binding::ProjectView> for neutral::ProjectView {
    type Error = SdkError;
    fn try_from(value: binding::ProjectView) -> AdapterResult<Self> {
        Ok(match value {
            binding::ProjectView::List => Self::List,
            binding::ProjectView::Board => Self::Board,
            binding::ProjectView::Calendar => Self::Calendar,
        })
    }
}

impl From<neutral::LogLevel> for binding::LogLevel {
    fn from(value: neutral::LogLevel) -> Self {
        match value {
            neutral::LogLevel::Debug => Self::Debug,
            neutral::LogLevel::Info => Self::Info,
            neutral::LogLevel::Warn => Self::Warn,
            neutral::LogLevel::Error => Self::Error,
        }
    }
}

impl TryFrom<binding::LogLevel> for neutral::LogLevel {
    type Error = SdkError;
    fn try_from(value: binding::LogLevel) -> AdapterResult<Self> {
        Ok(match value {
            binding::LogLevel::Debug => Self::Debug,
            binding::LogLevel::Info => Self::Info,
            binding::LogLevel::Warn => Self::Warn,
            binding::LogLevel::Error => Self::Error,
        })
    }
}

impl From<neutral::ErrorCode> for binding::ErrorCode {
    fn from(value: neutral::ErrorCode) -> Self {
        match value {
            neutral::ErrorCode::InvalidInput => Self::InvalidInput,
            neutral::ErrorCode::NotFound => Self::NotFound,
            neutral::ErrorCode::Conflict => Self::Conflict,
            neutral::ErrorCode::CursorStale => Self::CursorStale,
            neutral::ErrorCode::PermissionDenied => Self::PermissionDenied,
            neutral::ErrorCode::Unavailable => Self::Unavailable,
            neutral::ErrorCode::RateLimited => Self::RateLimited,
            neutral::ErrorCode::Cancelled => Self::Cancelled,
            neutral::ErrorCode::Internal => Self::Internal,
        }
    }
}

impl TryFrom<binding::ErrorCode> for neutral::ErrorCode {
    type Error = SdkError;
    fn try_from(value: binding::ErrorCode) -> AdapterResult<Self> {
        Ok(match value {
            binding::ErrorCode::InvalidInput => Self::InvalidInput,
            binding::ErrorCode::NotFound => Self::NotFound,
            binding::ErrorCode::Conflict => Self::Conflict,
            binding::ErrorCode::CursorStale => Self::CursorStale,
            binding::ErrorCode::PermissionDenied => Self::PermissionDenied,
            binding::ErrorCode::Unavailable => Self::Unavailable,
            binding::ErrorCode::RateLimited => Self::RateLimited,
            binding::ErrorCode::Cancelled => Self::Cancelled,
            binding::ErrorCode::Internal => Self::Internal,
        })
    }
}

impl From<neutral::HostError> for binding::HostError {
    fn from(value: neutral::HostError) -> Self {
        Self {
            code: value.code.into(),
            field: value.field,
            message: value.message,
        }
    }
}

impl TryFrom<binding::HostError> for neutral::HostError {
    type Error = SdkError;
    fn try_from(value: binding::HostError) -> AdapterResult<Self> {
        Ok(Self {
            code: value.code.try_into()?,
            field: value.field,
            message: value.message,
        })
    }
}

impl From<neutral::PluginError> for binding::PluginError {
    fn from(value: neutral::PluginError) -> Self {
        Self {
            code: value.code.into(),
            field: value.field,
            message: value.message,
        }
    }
}

impl TryFrom<binding::PluginError> for neutral::PluginError {
    type Error = SdkError;
    fn try_from(value: binding::PluginError) -> AdapterResult<Self> {
        Ok(Self {
            code: value.code.try_into()?,
            field: value.field,
            message: value.message,
        })
    }
}

impl From<neutral::ScalarValue> for binding::ScalarValue {
    fn from(value: neutral::ScalarValue) -> Self {
        match value {
            neutral::ScalarValue::StringValue(payload) => Self::StringValue(payload),
            neutral::ScalarValue::IntegerValue(payload) => Self::IntegerValue(payload),
            neutral::ScalarValue::BooleanValue(payload) => Self::BooleanValue(payload),
            neutral::ScalarValue::DateValue(payload) => Self::DateValue(payload),
            neutral::ScalarValue::TimestampValue(payload) => Self::TimestampValue(payload),
            neutral::ScalarValue::TaskId(payload) => Self::TaskId(payload),
            neutral::ScalarValue::ProjectId(payload) => Self::ProjectId(payload),
            neutral::ScalarValue::TagId(payload) => Self::TagId(payload),
            neutral::ScalarValue::PluginId(payload) => Self::PluginId(payload),
            neutral::ScalarValue::OptionId(payload) => Self::OptionId(payload),
        }
    }
}

impl TryFrom<binding::ScalarValue> for neutral::ScalarValue {
    type Error = SdkError;
    fn try_from(value: binding::ScalarValue) -> AdapterResult<Self> {
        Ok(match value {
            binding::ScalarValue::StringValue(payload) => Self::StringValue(payload),
            binding::ScalarValue::IntegerValue(payload) => Self::IntegerValue(payload),
            binding::ScalarValue::BooleanValue(payload) => Self::BooleanValue(payload),
            binding::ScalarValue::DateValue(payload) => Self::DateValue(payload),
            binding::ScalarValue::TimestampValue(payload) => Self::TimestampValue(payload),
            binding::ScalarValue::TaskId(payload) => Self::TaskId(payload),
            binding::ScalarValue::ProjectId(payload) => Self::ProjectId(payload),
            binding::ScalarValue::TagId(payload) => Self::TagId(payload),
            binding::ScalarValue::PluginId(payload) => Self::PluginId(payload),
            binding::ScalarValue::OptionId(payload) => Self::OptionId(payload),
        })
    }
}

impl From<neutral::DataValue> for binding::DataValue {
    fn from(value: neutral::DataValue) -> Self {
        match value {
            neutral::DataValue::Scalar(payload) => Self::Scalar(payload.into()),
            neutral::DataValue::StringList(payload) => Self::StringList(payload),
            neutral::DataValue::IntegerList(payload) => Self::IntegerList(payload),
            neutral::DataValue::BooleanList(payload) => Self::BooleanList(payload),
            neutral::DataValue::DateList(payload) => Self::DateList(payload),
            neutral::DataValue::TimestampList(payload) => Self::TimestampList(payload),
            neutral::DataValue::TaskIdList(payload) => Self::TaskIdList(payload),
            neutral::DataValue::ProjectIdList(payload) => Self::ProjectIdList(payload),
            neutral::DataValue::TagIdList(payload) => Self::TagIdList(payload),
            neutral::DataValue::PluginIdList(payload) => Self::PluginIdList(payload),
            neutral::DataValue::OptionIdList(payload) => Self::OptionIdList(payload),
        }
    }
}

impl TryFrom<binding::DataValue> for neutral::DataValue {
    type Error = SdkError;
    fn try_from(value: binding::DataValue) -> AdapterResult<Self> {
        Ok(match value {
            binding::DataValue::Scalar(payload) => Self::Scalar(payload.try_into()?),
            binding::DataValue::StringList(payload) => Self::StringList(payload),
            binding::DataValue::IntegerList(payload) => Self::IntegerList(payload),
            binding::DataValue::BooleanList(payload) => Self::BooleanList(payload),
            binding::DataValue::DateList(payload) => Self::DateList(payload),
            binding::DataValue::TimestampList(payload) => Self::TimestampList(payload),
            binding::DataValue::TaskIdList(payload) => Self::TaskIdList(payload),
            binding::DataValue::ProjectIdList(payload) => Self::ProjectIdList(payload),
            binding::DataValue::TagIdList(payload) => Self::TagIdList(payload),
            binding::DataValue::PluginIdList(payload) => Self::PluginIdList(payload),
            binding::DataValue::OptionIdList(payload) => Self::OptionIdList(payload),
        })
    }
}

impl From<neutral::NamedValue> for binding::NamedValue {
    fn from(value: neutral::NamedValue) -> Self {
        Self {
            name: value.name,
            value: value.value.into(),
        }
    }
}

impl TryFrom<binding::NamedValue> for neutral::NamedValue {
    type Error = SdkError;
    fn try_from(value: binding::NamedValue) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name,
            value: value.value.try_into()?,
        })
    }
}

impl From<neutral::ScalarNamedValue> for binding::ScalarNamedValue {
    fn from(value: neutral::ScalarNamedValue) -> Self {
        Self {
            name: value.name,
            value: value.value.into(),
        }
    }
}

impl TryFrom<binding::ScalarNamedValue> for neutral::ScalarNamedValue {
    type Error = SdkError;
    fn try_from(value: binding::ScalarNamedValue) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name,
            value: value.value.try_into()?,
        })
    }
}

impl From<neutral::InvocationContext> for binding::InvocationContext {
    fn from(value: neutral::InvocationContext) -> Self {
        Self {
            plugin_id: value.plugin_id,
            package_generation: value.package_generation,
            activation_epoch: value.activation_epoch,
            host_session_id: value.host_session_id,
            invocation_id: value.invocation_id,
            entry_id: value.entry_id,
        }
    }
}

impl TryFrom<binding::InvocationContext> for neutral::InvocationContext {
    type Error = SdkError;
    fn try_from(value: binding::InvocationContext) -> AdapterResult<Self> {
        Ok(Self {
            plugin_id: value.plugin_id,
            package_generation: value.package_generation,
            activation_epoch: value.activation_epoch,
            host_session_id: value.host_session_id,
            invocation_id: value.invocation_id,
            entry_id: value.entry_id,
        })
    }
}

impl From<neutral::LocalDueTime> for binding::LocalDueTime {
    fn from(value: neutral::LocalDueTime) -> Self {
        Self {
            time: value.time,
            time_zone: value.time_zone,
        }
    }
}

impl TryFrom<binding::LocalDueTime> for neutral::LocalDueTime {
    type Error = SdkError;
    fn try_from(value: binding::LocalDueTime) -> AdapterResult<Self> {
        Ok(Self {
            time: value.time,
            time_zone: value.time_zone,
        })
    }
}

impl From<neutral::TaskQuery> for binding::TaskQuery {
    fn from(value: neutral::TaskQuery) -> Self {
        Self {
            task_id: value.task_id,
            project_id: value.project_id,
            section_id: value.section_id,
            parent_id: value.parent_id,
            tag_ids: value.tag_ids,
            statuses: value.statuses.into_iter().map(|value| value.into()).collect(),
            priorities: value.priorities.into_iter().map(|value| value.into()).collect(),
            due_from: value.due_from,
            due_before: value.due_before,
            search: value.search,
            cursor: value.cursor,
            limit: value.limit,
        }
    }
}

impl TryFrom<binding::TaskQuery> for neutral::TaskQuery {
    type Error = SdkError;
    fn try_from(value: binding::TaskQuery) -> AdapterResult<Self> {
        Ok(Self {
            task_id: value.task_id,
            project_id: value.project_id,
            section_id: value.section_id,
            parent_id: value.parent_id,
            tag_ids: value.tag_ids,
            statuses: value.statuses.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            priorities: value.priorities.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            due_from: value.due_from,
            due_before: value.due_before,
            search: value.search,
            cursor: value.cursor,
            limit: value.limit,
        })
    }
}

impl From<neutral::TaskView> for binding::TaskView {
    fn from(value: neutral::TaskView) -> Self {
        Self {
            id: value.id,
            title: value.title,
            description: value.description,
            status: value.status.into(),
            priority: value.priority.map(|value| value.into()),
            due_date: value.due_date,
            due_time: value.due_time.map(|value| value.into()),
            deadline: value.deadline,
            someday: value.someday,
            estimated_minutes: value.estimated_minutes,
            actual_minutes: value.actual_minutes,
            dread: value.dread,
            project_id: value.project_id,
            section_id: value.section_id,
            parent_id: value.parent_id,
            tag_ids: value.tag_ids,
            sort_order: value.sort_order,
            recurrence_rule: value.recurrence_rule,
            remind_at: value.remind_at,
            recurrence_anchor_day: value.recurrence_anchor_day,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        }
    }
}

impl TryFrom<binding::TaskView> for neutral::TaskView {
    type Error = SdkError;
    fn try_from(value: binding::TaskView) -> AdapterResult<Self> {
        Ok(Self {
            id: value.id,
            title: value.title,
            description: value.description,
            status: value.status.try_into()?,
            priority: match value.priority { Some(value) => Some(value.try_into()?), None => None },
            due_date: value.due_date,
            due_time: match value.due_time { Some(value) => Some(value.try_into()?), None => None },
            deadline: value.deadline,
            someday: value.someday,
            estimated_minutes: value.estimated_minutes,
            actual_minutes: value.actual_minutes,
            dread: value.dread,
            project_id: value.project_id,
            section_id: value.section_id,
            parent_id: value.parent_id,
            tag_ids: value.tag_ids,
            sort_order: value.sort_order,
            recurrence_rule: value.recurrence_rule,
            remind_at: value.remind_at,
            recurrence_anchor_day: value.recurrence_anchor_day,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        })
    }
}

impl From<neutral::TaskPage> for binding::TaskPage {
    fn from(value: neutral::TaskPage) -> Self {
        Self {
            items: value.items.into_iter().map(|value| value.into()).collect(),
            next_cursor: value.next_cursor,
            revision: value.revision,
        }
    }
}

impl TryFrom<binding::TaskPage> for neutral::TaskPage {
    type Error = SdkError;
    fn try_from(value: binding::TaskPage) -> AdapterResult<Self> {
        Ok(Self {
            items: value.items.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            next_cursor: value.next_cursor,
            revision: value.revision,
        })
    }
}

impl From<neutral::CatalogQuery> for binding::CatalogQuery {
    fn from(value: neutral::CatalogQuery) -> Self {
        Self {
            cursor: value.cursor,
            limit: value.limit,
        }
    }
}

impl TryFrom<binding::CatalogQuery> for neutral::CatalogQuery {
    type Error = SdkError;
    fn try_from(value: binding::CatalogQuery) -> AdapterResult<Self> {
        Ok(Self {
            cursor: value.cursor,
            limit: value.limit,
        })
    }
}

impl From<neutral::ProjectViewRecord> for binding::ProjectViewRecord {
    fn from(value: neutral::ProjectViewRecord) -> Self {
        Self {
            id: value.id,
            name: value.name,
            color: value.color,
            icon: value.icon,
            parent_id: value.parent_id,
            favorite: value.favorite,
            archived: value.archived,
            view: value.view.into(),
            sort_order: value.sort_order,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        }
    }
}

impl TryFrom<binding::ProjectViewRecord> for neutral::ProjectViewRecord {
    type Error = SdkError;
    fn try_from(value: binding::ProjectViewRecord) -> AdapterResult<Self> {
        Ok(Self {
            id: value.id,
            name: value.name,
            color: value.color,
            icon: value.icon,
            parent_id: value.parent_id,
            favorite: value.favorite,
            archived: value.archived,
            view: value.view.try_into()?,
            sort_order: value.sort_order,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        })
    }
}

impl From<neutral::ProjectPage> for binding::ProjectPage {
    fn from(value: neutral::ProjectPage) -> Self {
        Self {
            items: value.items.into_iter().map(|value| value.into()).collect(),
            next_cursor: value.next_cursor,
            revision: value.revision,
        }
    }
}

impl TryFrom<binding::ProjectPage> for neutral::ProjectPage {
    type Error = SdkError;
    fn try_from(value: binding::ProjectPage) -> AdapterResult<Self> {
        Ok(Self {
            items: value.items.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            next_cursor: value.next_cursor,
            revision: value.revision,
        })
    }
}

impl From<neutral::TagView> for binding::TagView {
    fn from(value: neutral::TagView) -> Self {
        Self {
            id: value.id,
            name: value.name,
            color: value.color,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        }
    }
}

impl TryFrom<binding::TagView> for neutral::TagView {
    type Error = SdkError;
    fn try_from(value: binding::TagView) -> AdapterResult<Self> {
        Ok(Self {
            id: value.id,
            name: value.name,
            color: value.color,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        })
    }
}

impl From<neutral::TagPage> for binding::TagPage {
    fn from(value: neutral::TagPage) -> Self {
        Self {
            items: value.items.into_iter().map(|value| value.into()).collect(),
            next_cursor: value.next_cursor,
            revision: value.revision,
        }
    }
}

impl TryFrom<binding::TagPage> for neutral::TagPage {
    type Error = SdkError;
    fn try_from(value: binding::TagPage) -> AdapterResult<Self> {
        Ok(Self {
            items: value.items.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            next_cursor: value.next_cursor,
            revision: value.revision,
        })
    }
}

impl From<neutral::SectionView> for binding::SectionView {
    fn from(value: neutral::SectionView) -> Self {
        Self {
            id: value.id,
            project_id: value.project_id,
            name: value.name,
            collapsed: value.collapsed,
            sort_order: value.sort_order,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        }
    }
}

impl TryFrom<binding::SectionView> for neutral::SectionView {
    type Error = SdkError;
    fn try_from(value: binding::SectionView) -> AdapterResult<Self> {
        Ok(Self {
            id: value.id,
            project_id: value.project_id,
            name: value.name,
            collapsed: value.collapsed,
            sort_order: value.sort_order,
            created_at: value.created_at,
            updated_at: value.updated_at,
            revision: value.revision,
        })
    }
}

impl From<neutral::StringChange> for binding::StringChange {
    fn from(value: neutral::StringChange) -> Self {
        match value {
            neutral::StringChange::Unchanged(()) => Self::Unchanged,
            neutral::StringChange::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::StringChange> for neutral::StringChange {
    type Error = SdkError;
    fn try_from(value: binding::StringChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::StringChange::Unchanged => Self::Unchanged(()),
            binding::StringChange::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::BoolChange> for binding::BoolChange {
    fn from(value: neutral::BoolChange) -> Self {
        match value {
            neutral::BoolChange::Unchanged(()) => Self::Unchanged,
            neutral::BoolChange::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::BoolChange> for neutral::BoolChange {
    type Error = SdkError;
    fn try_from(value: binding::BoolChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::BoolChange::Unchanged => Self::Unchanged(()),
            binding::BoolChange::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::S64Change> for binding::S64Change {
    fn from(value: neutral::S64Change) -> Self {
        match value {
            neutral::S64Change::Unchanged(()) => Self::Unchanged,
            neutral::S64Change::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::S64Change> for neutral::S64Change {
    type Error = SdkError;
    fn try_from(value: binding::S64Change) -> AdapterResult<Self> {
        Ok(match value {
            binding::S64Change::Unchanged => Self::Unchanged(()),
            binding::S64Change::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::ProjectViewChange> for binding::ProjectViewChange {
    fn from(value: neutral::ProjectViewChange) -> Self {
        match value {
            neutral::ProjectViewChange::Unchanged(()) => Self::Unchanged,
            neutral::ProjectViewChange::Set(payload) => Self::Set(payload.into()),
        }
    }
}

impl TryFrom<binding::ProjectViewChange> for neutral::ProjectViewChange {
    type Error = SdkError;
    fn try_from(value: binding::ProjectViewChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::ProjectViewChange::Unchanged => Self::Unchanged(()),
            binding::ProjectViewChange::Set(payload) => Self::Set(payload.try_into()?),
        })
    }
}

impl From<neutral::OptionalStringChange> for binding::OptionalStringChange {
    fn from(value: neutral::OptionalStringChange) -> Self {
        match value {
            neutral::OptionalStringChange::Unchanged(()) => Self::Unchanged,
            neutral::OptionalStringChange::Clear(()) => Self::Clear,
            neutral::OptionalStringChange::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::OptionalStringChange> for neutral::OptionalStringChange {
    type Error = SdkError;
    fn try_from(value: binding::OptionalStringChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalStringChange::Unchanged => Self::Unchanged(()),
            binding::OptionalStringChange::Clear => Self::Clear(()),
            binding::OptionalStringChange::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::OptionalIdChange> for binding::OptionalIdChange {
    fn from(value: neutral::OptionalIdChange) -> Self {
        match value {
            neutral::OptionalIdChange::Unchanged(()) => Self::Unchanged,
            neutral::OptionalIdChange::Clear(()) => Self::Clear,
            neutral::OptionalIdChange::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::OptionalIdChange> for neutral::OptionalIdChange {
    type Error = SdkError;
    fn try_from(value: binding::OptionalIdChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalIdChange::Unchanged => Self::Unchanged(()),
            binding::OptionalIdChange::Clear => Self::Clear(()),
            binding::OptionalIdChange::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::OptionalDateChange> for binding::OptionalDateChange {
    fn from(value: neutral::OptionalDateChange) -> Self {
        match value {
            neutral::OptionalDateChange::Unchanged(()) => Self::Unchanged,
            neutral::OptionalDateChange::Clear(()) => Self::Clear,
            neutral::OptionalDateChange::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::OptionalDateChange> for neutral::OptionalDateChange {
    type Error = SdkError;
    fn try_from(value: binding::OptionalDateChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalDateChange::Unchanged => Self::Unchanged(()),
            binding::OptionalDateChange::Clear => Self::Clear(()),
            binding::OptionalDateChange::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::OptionalTimestampChange> for binding::OptionalTimestampChange {
    fn from(value: neutral::OptionalTimestampChange) -> Self {
        match value {
            neutral::OptionalTimestampChange::Unchanged(()) => Self::Unchanged,
            neutral::OptionalTimestampChange::Clear(()) => Self::Clear,
            neutral::OptionalTimestampChange::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::OptionalTimestampChange> for neutral::OptionalTimestampChange {
    type Error = SdkError;
    fn try_from(value: binding::OptionalTimestampChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalTimestampChange::Unchanged => Self::Unchanged(()),
            binding::OptionalTimestampChange::Clear => Self::Clear(()),
            binding::OptionalTimestampChange::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::OptionalLocalDueTimeChange> for binding::OptionalLocalDueTimeChange {
    fn from(value: neutral::OptionalLocalDueTimeChange) -> Self {
        match value {
            neutral::OptionalLocalDueTimeChange::Unchanged(()) => Self::Unchanged,
            neutral::OptionalLocalDueTimeChange::Clear(()) => Self::Clear,
            neutral::OptionalLocalDueTimeChange::Set(payload) => Self::Set(payload.into()),
        }
    }
}

impl TryFrom<binding::OptionalLocalDueTimeChange> for neutral::OptionalLocalDueTimeChange {
    type Error = SdkError;
    fn try_from(value: binding::OptionalLocalDueTimeChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalLocalDueTimeChange::Unchanged => Self::Unchanged(()),
            binding::OptionalLocalDueTimeChange::Clear => Self::Clear(()),
            binding::OptionalLocalDueTimeChange::Set(payload) => Self::Set(payload.try_into()?),
        })
    }
}

impl From<neutral::OptionalU32Change> for binding::OptionalU32Change {
    fn from(value: neutral::OptionalU32Change) -> Self {
        match value {
            neutral::OptionalU32Change::Unchanged(()) => Self::Unchanged,
            neutral::OptionalU32Change::Clear(()) => Self::Clear,
            neutral::OptionalU32Change::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::OptionalU32Change> for neutral::OptionalU32Change {
    type Error = SdkError;
    fn try_from(value: binding::OptionalU32Change) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalU32Change::Unchanged => Self::Unchanged(()),
            binding::OptionalU32Change::Clear => Self::Clear(()),
            binding::OptionalU32Change::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::OptionalU8Change> for binding::OptionalU8Change {
    fn from(value: neutral::OptionalU8Change) -> Self {
        match value {
            neutral::OptionalU8Change::Unchanged(()) => Self::Unchanged,
            neutral::OptionalU8Change::Clear(()) => Self::Clear,
            neutral::OptionalU8Change::Set(payload) => Self::Set(payload),
        }
    }
}

impl TryFrom<binding::OptionalU8Change> for neutral::OptionalU8Change {
    type Error = SdkError;
    fn try_from(value: binding::OptionalU8Change) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalU8Change::Unchanged => Self::Unchanged(()),
            binding::OptionalU8Change::Clear => Self::Clear(()),
            binding::OptionalU8Change::Set(payload) => Self::Set(payload),
        })
    }
}

impl From<neutral::OptionalPriorityChange> for binding::OptionalPriorityChange {
    fn from(value: neutral::OptionalPriorityChange) -> Self {
        match value {
            neutral::OptionalPriorityChange::Unchanged(()) => Self::Unchanged,
            neutral::OptionalPriorityChange::Clear(()) => Self::Clear,
            neutral::OptionalPriorityChange::Set(payload) => Self::Set(payload.into()),
        }
    }
}

impl TryFrom<binding::OptionalPriorityChange> for neutral::OptionalPriorityChange {
    type Error = SdkError;
    fn try_from(value: binding::OptionalPriorityChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::OptionalPriorityChange::Unchanged => Self::Unchanged(()),
            binding::OptionalPriorityChange::Clear => Self::Clear(()),
            binding::OptionalPriorityChange::Set(payload) => Self::Set(payload.try_into()?),
        })
    }
}

impl From<neutral::IdListChange> for binding::IdListChange {
    fn from(value: neutral::IdListChange) -> Self {
        match value {
            neutral::IdListChange::Unchanged(()) => Self::Unchanged,
            neutral::IdListChange::Replace(payload) => Self::Replace(payload),
        }
    }
}

impl TryFrom<binding::IdListChange> for neutral::IdListChange {
    type Error = SdkError;
    fn try_from(value: binding::IdListChange) -> AdapterResult<Self> {
        Ok(match value {
            binding::IdListChange::Unchanged => Self::Unchanged(()),
            binding::IdListChange::Replace(payload) => Self::Replace(payload),
        })
    }
}

impl From<neutral::TaskDraft> for binding::TaskDraft {
    fn from(value: neutral::TaskDraft) -> Self {
        Self {
            title: value.title,
            description: value.description,
            priority: value.priority.map(|value| value.into()),
            due_date: value.due_date,
            due_time: value.due_time.map(|value| value.into()),
            deadline: value.deadline,
            someday: value.someday,
            estimated_minutes: value.estimated_minutes,
            actual_minutes: value.actual_minutes,
            dread: value.dread,
            project_id: value.project_id,
            section_id: value.section_id,
            parent_id: value.parent_id,
            tag_ids: value.tag_ids,
            sort_order: value.sort_order,
            recurrence_rule: value.recurrence_rule,
            remind_at: value.remind_at,
            recurrence_anchor_day: value.recurrence_anchor_day,
        }
    }
}

impl TryFrom<binding::TaskDraft> for neutral::TaskDraft {
    type Error = SdkError;
    fn try_from(value: binding::TaskDraft) -> AdapterResult<Self> {
        Ok(Self {
            title: value.title,
            description: value.description,
            priority: match value.priority { Some(value) => Some(value.try_into()?), None => None },
            due_date: value.due_date,
            due_time: match value.due_time { Some(value) => Some(value.try_into()?), None => None },
            deadline: value.deadline,
            someday: value.someday,
            estimated_minutes: value.estimated_minutes,
            actual_minutes: value.actual_minutes,
            dread: value.dread,
            project_id: value.project_id,
            section_id: value.section_id,
            parent_id: value.parent_id,
            tag_ids: value.tag_ids,
            sort_order: value.sort_order,
            recurrence_rule: value.recurrence_rule,
            remind_at: value.remind_at,
            recurrence_anchor_day: value.recurrence_anchor_day,
        })
    }
}

impl From<neutral::TaskPatch> for binding::TaskPatch {
    fn from(value: neutral::TaskPatch) -> Self {
        Self {
            title: value.title.into(),
            description: value.description.into(),
            priority: value.priority.into(),
            due_date: value.due_date.into(),
            due_time: value.due_time.into(),
            deadline: value.deadline.into(),
            someday: value.someday.into(),
            estimated_minutes: value.estimated_minutes.into(),
            actual_minutes: value.actual_minutes.into(),
            dread: value.dread.into(),
            project_id: value.project_id.into(),
            section_id: value.section_id.into(),
            parent_id: value.parent_id.into(),
            tag_ids: value.tag_ids.into(),
            sort_order: value.sort_order.into(),
            recurrence_rule: value.recurrence_rule.into(),
            remind_at: value.remind_at.into(),
            recurrence_anchor_day: value.recurrence_anchor_day.into(),
        }
    }
}

impl TryFrom<binding::TaskPatch> for neutral::TaskPatch {
    type Error = SdkError;
    fn try_from(value: binding::TaskPatch) -> AdapterResult<Self> {
        Ok(Self {
            title: value.title.try_into()?,
            description: value.description.try_into()?,
            priority: value.priority.try_into()?,
            due_date: value.due_date.try_into()?,
            due_time: value.due_time.try_into()?,
            deadline: value.deadline.try_into()?,
            someday: value.someday.try_into()?,
            estimated_minutes: value.estimated_minutes.try_into()?,
            actual_minutes: value.actual_minutes.try_into()?,
            dread: value.dread.try_into()?,
            project_id: value.project_id.try_into()?,
            section_id: value.section_id.try_into()?,
            parent_id: value.parent_id.try_into()?,
            tag_ids: value.tag_ids.try_into()?,
            sort_order: value.sort_order.try_into()?,
            recurrence_rule: value.recurrence_rule.try_into()?,
            remind_at: value.remind_at.try_into()?,
            recurrence_anchor_day: value.recurrence_anchor_day.try_into()?,
        })
    }
}

impl From<neutral::PatchTask> for binding::PatchTask {
    fn from(value: neutral::PatchTask) -> Self {
        Self {
            task_id: value.task_id,
            patch: value.patch.into(),
        }
    }
}

impl TryFrom<binding::PatchTask> for neutral::PatchTask {
    type Error = SdkError;
    fn try_from(value: binding::PatchTask) -> AdapterResult<Self> {
        Ok(Self {
            task_id: value.task_id,
            patch: value.patch.try_into()?,
        })
    }
}

impl From<neutral::BulkMove> for binding::BulkMove {
    fn from(value: neutral::BulkMove) -> Self {
        Self {
            project_id: value.project_id.into(),
            section_id: value.section_id.into(),
            parent_id: value.parent_id.into(),
        }
    }
}

impl TryFrom<binding::BulkMove> for neutral::BulkMove {
    type Error = SdkError;
    fn try_from(value: binding::BulkMove) -> AdapterResult<Self> {
        Ok(Self {
            project_id: value.project_id.try_into()?,
            section_id: value.section_id.try_into()?,
            parent_id: value.parent_id.try_into()?,
        })
    }
}

impl From<neutral::BulkTag> for binding::BulkTag {
    fn from(value: neutral::BulkTag) -> Self {
        Self {
            add: value.add,
            remove: value.remove,
        }
    }
}

impl TryFrom<binding::BulkTag> for neutral::BulkTag {
    type Error = SdkError;
    fn try_from(value: binding::BulkTag) -> AdapterResult<Self> {
        Ok(Self {
            add: value.add,
            remove: value.remove,
        })
    }
}

impl From<neutral::BulkSchedule> for binding::BulkSchedule {
    fn from(value: neutral::BulkSchedule) -> Self {
        Self {
            due_date: value.due_date.into(),
            due_time: value.due_time.into(),
            deadline: value.deadline.into(),
            someday: value.someday.into(),
        }
    }
}

impl TryFrom<binding::BulkSchedule> for neutral::BulkSchedule {
    type Error = SdkError;
    fn try_from(value: binding::BulkSchedule) -> AdapterResult<Self> {
        Ok(Self {
            due_date: value.due_date.try_into()?,
            due_time: value.due_time.try_into()?,
            deadline: value.deadline.try_into()?,
            someday: value.someday.try_into()?,
        })
    }
}

impl From<neutral::BulkPriority> for binding::BulkPriority {
    fn from(value: neutral::BulkPriority) -> Self {
        match value {
            neutral::BulkPriority::Clear(()) => Self::Clear,
            neutral::BulkPriority::Set(payload) => Self::Set(payload.into()),
        }
    }
}

impl TryFrom<binding::BulkPriority> for neutral::BulkPriority {
    type Error = SdkError;
    fn try_from(value: binding::BulkPriority) -> AdapterResult<Self> {
        Ok(match value {
            binding::BulkPriority::Clear => Self::Clear(()),
            binding::BulkPriority::Set(payload) => Self::Set(payload.try_into()?),
        })
    }
}

impl From<neutral::BulkAction> for binding::BulkAction {
    fn from(value: neutral::BulkAction) -> Self {
        match value {
            neutral::BulkAction::Complete(()) => Self::Complete,
            neutral::BulkAction::Uncomplete(()) => Self::Uncomplete,
            neutral::BulkAction::Cancel(()) => Self::Cancel,
            neutral::BulkAction::Reopen(()) => Self::Reopen,
            neutral::BulkAction::Delete(()) => Self::Delete,
            neutral::BulkAction::Move(payload) => Self::Move(payload.into()),
            neutral::BulkAction::Tag(payload) => Self::Tag(payload.into()),
            neutral::BulkAction::Schedule(payload) => Self::Schedule(payload.into()),
            neutral::BulkAction::Priority(payload) => Self::Priority(payload.into()),
        }
    }
}

impl TryFrom<binding::BulkAction> for neutral::BulkAction {
    type Error = SdkError;
    fn try_from(value: binding::BulkAction) -> AdapterResult<Self> {
        Ok(match value {
            binding::BulkAction::Complete => Self::Complete(()),
            binding::BulkAction::Uncomplete => Self::Uncomplete(()),
            binding::BulkAction::Cancel => Self::Cancel(()),
            binding::BulkAction::Reopen => Self::Reopen(()),
            binding::BulkAction::Delete => Self::Delete(()),
            binding::BulkAction::Move(payload) => Self::Move(payload.try_into()?),
            binding::BulkAction::Tag(payload) => Self::Tag(payload.try_into()?),
            binding::BulkAction::Schedule(payload) => Self::Schedule(payload.try_into()?),
            binding::BulkAction::Priority(payload) => Self::Priority(payload.try_into()?),
        })
    }
}

impl From<neutral::BulkTasks> for binding::BulkTasks {
    fn from(value: neutral::BulkTasks) -> Self {
        Self {
            task_ids: value.task_ids,
            action: value.action.into(),
        }
    }
}

impl TryFrom<binding::BulkTasks> for neutral::BulkTasks {
    type Error = SdkError;
    fn try_from(value: binding::BulkTasks) -> AdapterResult<Self> {
        Ok(Self {
            task_ids: value.task_ids,
            action: value.action.try_into()?,
        })
    }
}

impl From<neutral::ProjectDraft> for binding::ProjectDraft {
    fn from(value: neutral::ProjectDraft) -> Self {
        Self {
            name: value.name,
            color: value.color,
            icon: value.icon,
            parent_id: value.parent_id,
            favorite: value.favorite,
            archived: value.archived,
            view: value.view.into(),
            sort_order: value.sort_order,
        }
    }
}

impl TryFrom<binding::ProjectDraft> for neutral::ProjectDraft {
    type Error = SdkError;
    fn try_from(value: binding::ProjectDraft) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name,
            color: value.color,
            icon: value.icon,
            parent_id: value.parent_id,
            favorite: value.favorite,
            archived: value.archived,
            view: value.view.try_into()?,
            sort_order: value.sort_order,
        })
    }
}

impl From<neutral::ProjectPatch> for binding::ProjectPatch {
    fn from(value: neutral::ProjectPatch) -> Self {
        Self {
            name: value.name.into(),
            color: value.color.into(),
            icon: value.icon.into(),
            parent_id: value.parent_id.into(),
            favorite: value.favorite.into(),
            archived: value.archived.into(),
            view: value.view.into(),
            sort_order: value.sort_order.into(),
        }
    }
}

impl TryFrom<binding::ProjectPatch> for neutral::ProjectPatch {
    type Error = SdkError;
    fn try_from(value: binding::ProjectPatch) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name.try_into()?,
            color: value.color.try_into()?,
            icon: value.icon.try_into()?,
            parent_id: value.parent_id.try_into()?,
            favorite: value.favorite.try_into()?,
            archived: value.archived.try_into()?,
            view: value.view.try_into()?,
            sort_order: value.sort_order.try_into()?,
        })
    }
}

impl From<neutral::PatchProject> for binding::PatchProject {
    fn from(value: neutral::PatchProject) -> Self {
        Self {
            project_id: value.project_id,
            patch: value.patch.into(),
        }
    }
}

impl TryFrom<binding::PatchProject> for neutral::PatchProject {
    type Error = SdkError;
    fn try_from(value: binding::PatchProject) -> AdapterResult<Self> {
        Ok(Self {
            project_id: value.project_id,
            patch: value.patch.try_into()?,
        })
    }
}

impl From<neutral::TagDraft> for binding::TagDraft {
    fn from(value: neutral::TagDraft) -> Self {
        Self {
            name: value.name,
            color: value.color,
        }
    }
}

impl TryFrom<binding::TagDraft> for neutral::TagDraft {
    type Error = SdkError;
    fn try_from(value: binding::TagDraft) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name,
            color: value.color,
        })
    }
}

impl From<neutral::TagPatch> for binding::TagPatch {
    fn from(value: neutral::TagPatch) -> Self {
        Self {
            name: value.name.into(),
            color: value.color.into(),
        }
    }
}

impl TryFrom<binding::TagPatch> for neutral::TagPatch {
    type Error = SdkError;
    fn try_from(value: binding::TagPatch) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name.try_into()?,
            color: value.color.try_into()?,
        })
    }
}

impl From<neutral::PatchTag> for binding::PatchTag {
    fn from(value: neutral::PatchTag) -> Self {
        Self {
            tag_id: value.tag_id,
            patch: value.patch.into(),
        }
    }
}

impl TryFrom<binding::PatchTag> for neutral::PatchTag {
    type Error = SdkError;
    fn try_from(value: binding::PatchTag) -> AdapterResult<Self> {
        Ok(Self {
            tag_id: value.tag_id,
            patch: value.patch.try_into()?,
        })
    }
}

impl From<neutral::DomainMutation> for binding::DomainMutation {
    fn from(value: neutral::DomainMutation) -> Self {
        match value {
            neutral::DomainMutation::CreateTask(payload) => Self::CreateTask(payload.into()),
            neutral::DomainMutation::PatchTask(payload) => Self::PatchTask(payload.into()),
            neutral::DomainMutation::CompleteTask(payload) => Self::CompleteTask(payload),
            neutral::DomainMutation::UncompleteTask(payload) => Self::UncompleteTask(payload),
            neutral::DomainMutation::CancelTask(payload) => Self::CancelTask(payload),
            neutral::DomainMutation::ReopenTask(payload) => Self::ReopenTask(payload),
            neutral::DomainMutation::DeleteTask(payload) => Self::DeleteTask(payload),
            neutral::DomainMutation::BulkTasks(payload) => Self::BulkTasks(payload.into()),
            neutral::DomainMutation::CreateProject(payload) => Self::CreateProject(payload.into()),
            neutral::DomainMutation::PatchProject(payload) => Self::PatchProject(payload.into()),
            neutral::DomainMutation::DeleteProject(payload) => Self::DeleteProject(payload),
            neutral::DomainMutation::CreateTag(payload) => Self::CreateTag(payload.into()),
            neutral::DomainMutation::PatchTag(payload) => Self::PatchTag(payload.into()),
            neutral::DomainMutation::DeleteTag(payload) => Self::DeleteTag(payload),
        }
    }
}

impl TryFrom<binding::DomainMutation> for neutral::DomainMutation {
    type Error = SdkError;
    fn try_from(value: binding::DomainMutation) -> AdapterResult<Self> {
        Ok(match value {
            binding::DomainMutation::CreateTask(payload) => Self::CreateTask(payload.try_into()?),
            binding::DomainMutation::PatchTask(payload) => Self::PatchTask(payload.try_into()?),
            binding::DomainMutation::CompleteTask(payload) => Self::CompleteTask(payload),
            binding::DomainMutation::UncompleteTask(payload) => Self::UncompleteTask(payload),
            binding::DomainMutation::CancelTask(payload) => Self::CancelTask(payload),
            binding::DomainMutation::ReopenTask(payload) => Self::ReopenTask(payload),
            binding::DomainMutation::DeleteTask(payload) => Self::DeleteTask(payload),
            binding::DomainMutation::BulkTasks(payload) => Self::BulkTasks(payload.try_into()?),
            binding::DomainMutation::CreateProject(payload) => Self::CreateProject(payload.try_into()?),
            binding::DomainMutation::PatchProject(payload) => Self::PatchProject(payload.try_into()?),
            binding::DomainMutation::DeleteProject(payload) => Self::DeleteProject(payload),
            binding::DomainMutation::CreateTag(payload) => Self::CreateTag(payload.try_into()?),
            binding::DomainMutation::PatchTag(payload) => Self::PatchTag(payload.try_into()?),
            binding::DomainMutation::DeleteTag(payload) => Self::DeleteTag(payload),
        })
    }
}

impl From<neutral::KvSet> for binding::KvSet {
    fn from(value: neutral::KvSet) -> Self {
        Self {
            key: value.key,
            value: value.value.into_vec(),
        }
    }
}

impl TryFrom<binding::KvSet> for neutral::KvSet {
    type Error = SdkError;
    fn try_from(value: binding::KvSet) -> AdapterResult<Self> {
        Ok(Self {
            key: value.key,
            value: neutral::ByteList::new(value.value)?,
        })
    }
}

impl From<neutral::KvOperation> for binding::KvOperation {
    fn from(value: neutral::KvOperation) -> Self {
        match value {
            neutral::KvOperation::Set(payload) => Self::Set(payload.into()),
            neutral::KvOperation::Delete(payload) => Self::Delete(payload),
        }
    }
}

impl TryFrom<binding::KvOperation> for neutral::KvOperation {
    type Error = SdkError;
    fn try_from(value: binding::KvOperation) -> AdapterResult<Self> {
        Ok(match value {
            binding::KvOperation::Set(payload) => Self::Set(payload.try_into()?),
            binding::KvOperation::Delete(payload) => Self::Delete(payload),
        })
    }
}

impl From<neutral::KvPatch> for binding::KvPatch {
    fn from(value: neutral::KvPatch) -> Self {
        Self {
            operations: value.operations.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::KvPatch> for neutral::KvPatch {
    type Error = SdkError;
    fn try_from(value: binding::KvPatch) -> AdapterResult<Self> {
        Ok(Self {
            operations: value.operations.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::PluginEffect> for binding::PluginEffect {
    fn from(value: neutral::PluginEffect) -> Self {
        match value {
            neutral::PluginEffect::DomainMutation(payload) => Self::DomainMutation(payload.into()),
            neutral::PluginEffect::KvPatch(payload) => Self::KvPatch(payload.into()),
        }
    }
}

impl TryFrom<binding::PluginEffect> for neutral::PluginEffect {
    type Error = SdkError;
    fn try_from(value: binding::PluginEffect) -> AdapterResult<Self> {
        Ok(match value {
            binding::PluginEffect::DomainMutation(payload) => Self::DomainMutation(payload.try_into()?),
            binding::PluginEffect::KvPatch(payload) => Self::KvPatch(payload.try_into()?),
        })
    }
}

impl From<neutral::PluginOutcome> for binding::PluginOutcome {
    fn from(value: neutral::PluginOutcome) -> Self {
        Self {
            effect: value.effect.map(|value| value.into()),
        }
    }
}

impl TryFrom<binding::PluginOutcome> for neutral::PluginOutcome {
    type Error = SdkError;
    fn try_from(value: binding::PluginOutcome) -> AdapterResult<Self> {
        Ok(Self {
            effect: match value.effect { Some(value) => Some(value.try_into()?), None => None },
        })
    }
}

impl From<neutral::CommandCall> for binding::CommandCall {
    fn from(value: neutral::CommandCall) -> Self {
        Self {
            command_id: value.command_id,
            values: value.values.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::CommandCall> for neutral::CommandCall {
    type Error = SdkError;
    fn try_from(value: binding::CommandCall) -> AdapterResult<Self> {
        Ok(Self {
            command_id: value.command_id,
            values: value.values.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::EventKind> for binding::EventKind {
    fn from(value: neutral::EventKind) -> Self {
        match value {
            neutral::EventKind::TaskCreated => Self::TaskCreated,
            neutral::EventKind::TaskUpdated => Self::TaskUpdated,
            neutral::EventKind::TaskCompleted => Self::TaskCompleted,
            neutral::EventKind::TaskUncompleted => Self::TaskUncompleted,
            neutral::EventKind::TaskCancelled => Self::TaskCancelled,
            neutral::EventKind::TaskReopened => Self::TaskReopened,
            neutral::EventKind::TaskDeleted => Self::TaskDeleted,
            neutral::EventKind::ProjectCreated => Self::ProjectCreated,
            neutral::EventKind::ProjectUpdated => Self::ProjectUpdated,
            neutral::EventKind::ProjectDeleted => Self::ProjectDeleted,
            neutral::EventKind::TagCreated => Self::TagCreated,
            neutral::EventKind::TagUpdated => Self::TagUpdated,
            neutral::EventKind::TagDeleted => Self::TagDeleted,
            neutral::EventKind::SectionCreated => Self::SectionCreated,
            neutral::EventKind::SectionUpdated => Self::SectionUpdated,
            neutral::EventKind::SectionDeleted => Self::SectionDeleted,
        }
    }
}

impl TryFrom<binding::EventKind> for neutral::EventKind {
    type Error = SdkError;
    fn try_from(value: binding::EventKind) -> AdapterResult<Self> {
        Ok(match value {
            binding::EventKind::TaskCreated => Self::TaskCreated,
            binding::EventKind::TaskUpdated => Self::TaskUpdated,
            binding::EventKind::TaskCompleted => Self::TaskCompleted,
            binding::EventKind::TaskUncompleted => Self::TaskUncompleted,
            binding::EventKind::TaskCancelled => Self::TaskCancelled,
            binding::EventKind::TaskReopened => Self::TaskReopened,
            binding::EventKind::TaskDeleted => Self::TaskDeleted,
            binding::EventKind::ProjectCreated => Self::ProjectCreated,
            binding::EventKind::ProjectUpdated => Self::ProjectUpdated,
            binding::EventKind::ProjectDeleted => Self::ProjectDeleted,
            binding::EventKind::TagCreated => Self::TagCreated,
            binding::EventKind::TagUpdated => Self::TagUpdated,
            binding::EventKind::TagDeleted => Self::TagDeleted,
            binding::EventKind::SectionCreated => Self::SectionCreated,
            binding::EventKind::SectionUpdated => Self::SectionUpdated,
            binding::EventKind::SectionDeleted => Self::SectionDeleted,
        })
    }
}

impl From<neutral::EventSubject> for binding::EventSubject {
    fn from(value: neutral::EventSubject) -> Self {
        match value {
            neutral::EventSubject::Task(payload) => Self::Task(payload.into()),
            neutral::EventSubject::Project(payload) => Self::Project(payload.into()),
            neutral::EventSubject::Tag(payload) => Self::Tag(payload.into()),
            neutral::EventSubject::Section(payload) => Self::Section(payload.into()),
            neutral::EventSubject::DeletedTask(payload) => Self::DeletedTask(payload),
            neutral::EventSubject::DeletedProject(payload) => Self::DeletedProject(payload),
            neutral::EventSubject::DeletedTag(payload) => Self::DeletedTag(payload),
            neutral::EventSubject::DeletedSection(payload) => Self::DeletedSection(payload),
        }
    }
}

impl TryFrom<binding::EventSubject> for neutral::EventSubject {
    type Error = SdkError;
    fn try_from(value: binding::EventSubject) -> AdapterResult<Self> {
        Ok(match value {
            binding::EventSubject::Task(payload) => Self::Task(payload.try_into()?),
            binding::EventSubject::Project(payload) => Self::Project(payload.try_into()?),
            binding::EventSubject::Tag(payload) => Self::Tag(payload.try_into()?),
            binding::EventSubject::Section(payload) => Self::Section(payload.try_into()?),
            binding::EventSubject::DeletedTask(payload) => Self::DeletedTask(payload),
            binding::EventSubject::DeletedProject(payload) => Self::DeletedProject(payload),
            binding::EventSubject::DeletedTag(payload) => Self::DeletedTag(payload),
            binding::EventSubject::DeletedSection(payload) => Self::DeletedSection(payload),
        })
    }
}

impl From<neutral::EventEnvelope> for binding::EventEnvelope {
    fn from(value: neutral::EventEnvelope) -> Self {
        Self {
            event_epoch: value.event_epoch,
            revision: value.revision,
            kind: value.kind.into(),
            subject: value.subject.into(),
        }
    }
}

impl TryFrom<binding::EventEnvelope> for neutral::EventEnvelope {
    type Error = SdkError;
    fn try_from(value: binding::EventEnvelope) -> AdapterResult<Self> {
        Ok(Self {
            event_epoch: value.event_epoch,
            revision: value.revision,
            kind: value.kind.try_into()?,
            subject: value.subject.try_into()?,
        })
    }
}

impl From<neutral::UiTone> for binding::UiTone {
    fn from(value: neutral::UiTone) -> Self {
        match value {
            neutral::UiTone::Neutral => Self::Neutral,
            neutral::UiTone::Accent => Self::Accent,
            neutral::UiTone::Positive => Self::Positive,
            neutral::UiTone::Warning => Self::Warning,
            neutral::UiTone::Danger => Self::Danger,
        }
    }
}

impl TryFrom<binding::UiTone> for neutral::UiTone {
    type Error = SdkError;
    fn try_from(value: binding::UiTone) -> AdapterResult<Self> {
        Ok(match value {
            binding::UiTone::Neutral => Self::Neutral,
            binding::UiTone::Accent => Self::Accent,
            binding::UiTone::Positive => Self::Positive,
            binding::UiTone::Warning => Self::Warning,
            binding::UiTone::Danger => Self::Danger,
        })
    }
}

impl From<neutral::UiSize> for binding::UiSize {
    fn from(value: neutral::UiSize) -> Self {
        match value {
            neutral::UiSize::Small => Self::Small,
            neutral::UiSize::Medium => Self::Medium,
            neutral::UiSize::Large => Self::Large,
        }
    }
}

impl TryFrom<binding::UiSize> for neutral::UiSize {
    type Error = SdkError;
    fn try_from(value: binding::UiSize) -> AdapterResult<Self> {
        Ok(match value {
            binding::UiSize::Small => Self::Small,
            binding::UiSize::Medium => Self::Medium,
            binding::UiSize::Large => Self::Large,
        })
    }
}

impl From<neutral::UiAlign> for binding::UiAlign {
    fn from(value: neutral::UiAlign) -> Self {
        match value {
            neutral::UiAlign::Start => Self::Start,
            neutral::UiAlign::Center => Self::Center,
            neutral::UiAlign::End => Self::End,
            neutral::UiAlign::Stretch => Self::Stretch,
        }
    }
}

impl TryFrom<binding::UiAlign> for neutral::UiAlign {
    type Error = SdkError;
    fn try_from(value: binding::UiAlign) -> AdapterResult<Self> {
        Ok(match value {
            binding::UiAlign::Start => Self::Start,
            binding::UiAlign::Center => Self::Center,
            binding::UiAlign::End => Self::End,
            binding::UiAlign::Stretch => Self::Stretch,
        })
    }
}

impl From<neutral::LayoutProps> for binding::LayoutProps {
    fn from(value: neutral::LayoutProps) -> Self {
        Self {
            gap: value.gap,
            align: value.align.into(),
        }
    }
}

impl TryFrom<binding::LayoutProps> for neutral::LayoutProps {
    type Error = SdkError;
    fn try_from(value: binding::LayoutProps) -> AdapterResult<Self> {
        Ok(Self {
            gap: value.gap,
            align: value.align.try_into()?,
        })
    }
}

impl From<neutral::TextProps> for binding::TextProps {
    fn from(value: neutral::TextProps) -> Self {
        Self {
            text: value.text,
            tone: value.tone.into(),
            size: value.size.into(),
        }
    }
}

impl TryFrom<binding::TextProps> for neutral::TextProps {
    type Error = SdkError;
    fn try_from(value: binding::TextProps) -> AdapterResult<Self> {
        Ok(Self {
            text: value.text,
            tone: value.tone.try_into()?,
            size: value.size.try_into()?,
        })
    }
}

impl From<neutral::MetricProps> for binding::MetricProps {
    fn from(value: neutral::MetricProps) -> Self {
        Self {
            label: value.label,
            value: value.value,
            tone: value.tone.into(),
        }
    }
}

impl TryFrom<binding::MetricProps> for neutral::MetricProps {
    type Error = SdkError;
    fn try_from(value: binding::MetricProps) -> AdapterResult<Self> {
        Ok(Self {
            label: value.label,
            value: value.value,
            tone: value.tone.try_into()?,
        })
    }
}

impl From<neutral::ProgressProps> for binding::ProgressProps {
    fn from(value: neutral::ProgressProps) -> Self {
        Self {
            label: value.label,
            value: value.value,
            maximum: value.maximum,
        }
    }
}

impl TryFrom<binding::ProgressProps> for neutral::ProgressProps {
    type Error = SdkError;
    fn try_from(value: binding::ProgressProps) -> AdapterResult<Self> {
        Ok(Self {
            label: value.label,
            value: value.value,
            maximum: value.maximum,
        })
    }
}

impl From<neutral::ButtonProps> for binding::ButtonProps {
    fn from(value: neutral::ButtonProps) -> Self {
        Self {
            label: value.label,
            action_id: value.action_id,
            tone: value.tone.into(),
            icon: value.icon,
        }
    }
}

impl TryFrom<binding::ButtonProps> for neutral::ButtonProps {
    type Error = SdkError;
    fn try_from(value: binding::ButtonProps) -> AdapterResult<Self> {
        Ok(Self {
            label: value.label,
            action_id: value.action_id,
            tone: value.tone.try_into()?,
            icon: value.icon,
        })
    }
}

impl From<neutral::InputProps> for binding::InputProps {
    fn from(value: neutral::InputProps) -> Self {
        Self {
            label: value.label,
            action_id: value.action_id,
            value: value.value.into(),
            options: value.options.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::InputProps> for neutral::InputProps {
    type Error = SdkError;
    fn try_from(value: binding::InputProps) -> AdapterResult<Self> {
        Ok(Self {
            label: value.label,
            action_id: value.action_id,
            value: value.value.try_into()?,
            options: value.options.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::TaskListProps> for binding::TaskListProps {
    fn from(value: neutral::TaskListProps) -> Self {
        Self {
            task_ids: value.task_ids,
        }
    }
}

impl TryFrom<binding::TaskListProps> for neutral::TaskListProps {
    type Error = SdkError;
    fn try_from(value: binding::TaskListProps) -> AdapterResult<Self> {
        Ok(Self {
            task_ids: value.task_ids,
        })
    }
}

impl From<neutral::UiContent> for binding::UiContent {
    fn from(value: neutral::UiContent) -> Self {
        match value {
            neutral::UiContent::Stack(payload) => Self::Stack(payload.into()),
            neutral::UiContent::Row(payload) => Self::Row(payload.into()),
            neutral::UiContent::Heading(payload) => Self::Heading(payload.into()),
            neutral::UiContent::Text(payload) => Self::Text(payload.into()),
            neutral::UiContent::Badge(payload) => Self::Badge(payload.into()),
            neutral::UiContent::Metric(payload) => Self::Metric(payload.into()),
            neutral::UiContent::Progress(payload) => Self::Progress(payload.into()),
            neutral::UiContent::Button(payload) => Self::Button(payload.into()),
            neutral::UiContent::TextInput(payload) => Self::TextInput(payload.into()),
            neutral::UiContent::NumberInput(payload) => Self::NumberInput(payload.into()),
            neutral::UiContent::Select(payload) => Self::Select(payload.into()),
            neutral::UiContent::Toggle(payload) => Self::Toggle(payload.into()),
            neutral::UiContent::TaskList(payload) => Self::TaskList(payload.into()),
            neutral::UiContent::TaskRef(payload) => Self::TaskRef(payload),
            neutral::UiContent::Divider(()) => Self::Divider,
            neutral::UiContent::EmptyState(payload) => Self::EmptyState(payload.into()),
            neutral::UiContent::ErrorState(payload) => Self::ErrorState(payload.into()),
        }
    }
}

impl TryFrom<binding::UiContent> for neutral::UiContent {
    type Error = SdkError;
    fn try_from(value: binding::UiContent) -> AdapterResult<Self> {
        Ok(match value {
            binding::UiContent::Stack(payload) => Self::Stack(payload.try_into()?),
            binding::UiContent::Row(payload) => Self::Row(payload.try_into()?),
            binding::UiContent::Heading(payload) => Self::Heading(payload.try_into()?),
            binding::UiContent::Text(payload) => Self::Text(payload.try_into()?),
            binding::UiContent::Badge(payload) => Self::Badge(payload.try_into()?),
            binding::UiContent::Metric(payload) => Self::Metric(payload.try_into()?),
            binding::UiContent::Progress(payload) => Self::Progress(payload.try_into()?),
            binding::UiContent::Button(payload) => Self::Button(payload.try_into()?),
            binding::UiContent::TextInput(payload) => Self::TextInput(payload.try_into()?),
            binding::UiContent::NumberInput(payload) => Self::NumberInput(payload.try_into()?),
            binding::UiContent::Select(payload) => Self::Select(payload.try_into()?),
            binding::UiContent::Toggle(payload) => Self::Toggle(payload.try_into()?),
            binding::UiContent::TaskList(payload) => Self::TaskList(payload.try_into()?),
            binding::UiContent::TaskRef(payload) => Self::TaskRef(payload),
            binding::UiContent::Divider => Self::Divider(()),
            binding::UiContent::EmptyState(payload) => Self::EmptyState(payload.try_into()?),
            binding::UiContent::ErrorState(payload) => Self::ErrorState(payload.try_into()?),
        })
    }
}

impl From<neutral::UiNode> for binding::UiNode {
    fn from(value: neutral::UiNode) -> Self {
        Self {
            id: value.id,
            parent_index: value.parent_index,
            content: value.content.into(),
        }
    }
}

impl TryFrom<binding::UiNode> for neutral::UiNode {
    type Error = SdkError;
    fn try_from(value: binding::UiNode) -> AdapterResult<Self> {
        Ok(Self {
            id: value.id,
            parent_index: value.parent_index,
            content: value.content.try_into()?,
        })
    }
}

impl From<neutral::Surface> for binding::Surface {
    fn from(value: neutral::Surface) -> Self {
        Self {
            surface_id: value.surface_id,
            root_index: value.root_index,
            nodes: value.nodes.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::Surface> for neutral::Surface {
    type Error = SdkError;
    fn try_from(value: binding::Surface) -> AdapterResult<Self> {
        Ok(Self {
            surface_id: value.surface_id,
            root_index: value.root_index,
            nodes: value.nodes.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::SurfaceRequest> for binding::SurfaceRequest {
    fn from(value: neutral::SurfaceRequest) -> Self {
        Self {
            surface_id: value.surface_id,
        }
    }
}

impl TryFrom<binding::SurfaceRequest> for neutral::SurfaceRequest {
    type Error = SdkError;
    fn try_from(value: binding::SurfaceRequest) -> AdapterResult<Self> {
        Ok(Self {
            surface_id: value.surface_id,
        })
    }
}

impl From<neutral::SurfaceAction> for binding::SurfaceAction {
    fn from(value: neutral::SurfaceAction) -> Self {
        Self {
            surface_id: value.surface_id,
            action_id: value.action_id,
            values: value.values.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::SurfaceAction> for neutral::SurfaceAction {
    type Error = SdkError;
    fn try_from(value: binding::SurfaceAction) -> AdapterResult<Self> {
        Ok(Self {
            surface_id: value.surface_id,
            action_id: value.action_id,
            values: value.values.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::SettingValue> for binding::SettingValue {
    fn from(value: neutral::SettingValue) -> Self {
        match value {
            neutral::SettingValue::Text(payload) => Self::Text(payload),
            neutral::SettingValue::Integer(payload) => Self::Integer(payload),
            neutral::SettingValue::Boolean(payload) => Self::Boolean(payload),
            neutral::SettingValue::OptionId(payload) => Self::OptionId(payload),
        }
    }
}

impl TryFrom<binding::SettingValue> for neutral::SettingValue {
    type Error = SdkError;
    fn try_from(value: binding::SettingValue) -> AdapterResult<Self> {
        Ok(match value {
            binding::SettingValue::Text(payload) => Self::Text(payload),
            binding::SettingValue::Integer(payload) => Self::Integer(payload),
            binding::SettingValue::Boolean(payload) => Self::Boolean(payload),
            binding::SettingValue::OptionId(payload) => Self::OptionId(payload),
        })
    }
}

impl From<neutral::NamedSetting> for binding::NamedSetting {
    fn from(value: neutral::NamedSetting) -> Self {
        Self {
            id: value.id,
            value: value.value.into(),
        }
    }
}

impl TryFrom<binding::NamedSetting> for neutral::NamedSetting {
    type Error = SdkError;
    fn try_from(value: binding::NamedSetting) -> AdapterResult<Self> {
        Ok(Self {
            id: value.id,
            value: value.value.try_into()?,
        })
    }
}

impl From<neutral::ValidationIssue> for binding::ValidationIssue {
    fn from(value: neutral::ValidationIssue) -> Self {
        Self {
            setting_id: value.setting_id,
            message: value.message,
        }
    }
}

impl TryFrom<binding::ValidationIssue> for neutral::ValidationIssue {
    type Error = SdkError;
    fn try_from(value: binding::ValidationIssue) -> AdapterResult<Self> {
        Ok(Self {
            setting_id: value.setting_id,
            message: value.message,
        })
    }
}

impl From<neutral::SettingValues> for binding::SettingValues {
    fn from(value: neutral::SettingValues) -> Self {
        Self {
            values: value.values.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::SettingValues> for neutral::SettingValues {
    type Error = SdkError;
    fn try_from(value: binding::SettingValues) -> AdapterResult<Self> {
        Ok(Self {
            values: value.values.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::ServiceCall> for binding::ServiceCall {
    fn from(value: neutral::ServiceCall) -> Self {
        Self {
            plugin_id: value.plugin_id,
            service_id: value.service_id,
            values: value.values.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::ServiceCall> for neutral::ServiceCall {
    type Error = SdkError;
    fn try_from(value: binding::ServiceCall) -> AdapterResult<Self> {
        Ok(Self {
            plugin_id: value.plugin_id,
            service_id: value.service_id,
            values: value.values.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::ServiceData> for binding::ServiceData {
    fn from(value: neutral::ServiceData) -> Self {
        Self {
            values: value.values.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::ServiceData> for neutral::ServiceData {
    type Error = SdkError;
    fn try_from(value: binding::ServiceData) -> AdapterResult<Self> {
        Ok(Self {
            values: value.values.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::ResourceKind> for binding::ResourceKind {
    fn from(value: neutral::ResourceKind) -> Self {
        match value {
            neutral::ResourceKind::Task => Self::Task,
            neutral::ResourceKind::Project => Self::Project,
            neutral::ResourceKind::Tag => Self::Tag,
        }
    }
}

impl TryFrom<binding::ResourceKind> for neutral::ResourceKind {
    type Error = SdkError;
    fn try_from(value: binding::ResourceKind) -> AdapterResult<Self> {
        Ok(match value {
            binding::ResourceKind::Task => Self::Task,
            binding::ResourceKind::Project => Self::Project,
            binding::ResourceKind::Tag => Self::Tag,
        })
    }
}

impl From<neutral::SnapshotRecords> for binding::SnapshotRecords {
    fn from(value: neutral::SnapshotRecords) -> Self {
        match value {
            neutral::SnapshotRecords::Tasks(payload) => Self::Tasks(payload.into_iter().map(|value| value.into()).collect()),
            neutral::SnapshotRecords::Projects(payload) => Self::Projects(payload.into_iter().map(|value| value.into()).collect()),
            neutral::SnapshotRecords::Tags(payload) => Self::Tags(payload.into_iter().map(|value| value.into()).collect()),
        }
    }
}

impl TryFrom<binding::SnapshotRecords> for neutral::SnapshotRecords {
    type Error = SdkError;
    fn try_from(value: binding::SnapshotRecords) -> AdapterResult<Self> {
        Ok(match value {
            binding::SnapshotRecords::Tasks(payload) => Self::Tasks(payload.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?),
            binding::SnapshotRecords::Projects(payload) => Self::Projects(payload.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?),
            binding::SnapshotRecords::Tags(payload) => Self::Tags(payload.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?),
        })
    }
}

impl From<neutral::SnapshotPage> for binding::SnapshotPage {
    fn from(value: neutral::SnapshotPage) -> Self {
        Self {
            session_id: value.session_id,
            event_epoch: value.event_epoch,
            head_revision: value.head_revision,
            kind: value.kind.into(),
            page_index: value.page_index,
            records: value.records.into(),
            final_snapshot_page: value.final_snapshot_page,
        }
    }
}

impl TryFrom<binding::SnapshotPage> for neutral::SnapshotPage {
    type Error = SdkError;
    fn try_from(value: binding::SnapshotPage) -> AdapterResult<Self> {
        Ok(Self {
            session_id: value.session_id,
            event_epoch: value.event_epoch,
            head_revision: value.head_revision,
            kind: value.kind.try_into()?,
            page_index: value.page_index,
            records: value.records.try_into()?,
            final_snapshot_page: value.final_snapshot_page,
        })
    }
}

impl From<neutral::FlushStagedKv> for binding::FlushStagedKv {
    fn from(value: neutral::FlushStagedKv) -> Self {
        Self {
            session_id: value.session_id,
            request_index: value.request_index,
        }
    }
}

impl TryFrom<binding::FlushStagedKv> for neutral::FlushStagedKv {
    type Error = SdkError;
    fn try_from(value: binding::FlushStagedKv) -> AdapterResult<Self> {
        Ok(Self {
            session_id: value.session_id,
            request_index: value.request_index,
        })
    }
}

impl From<neutral::FinalizeResync> for binding::FinalizeResync {
    fn from(value: neutral::FinalizeResync) -> Self {
        Self {
            session_id: value.session_id,
        }
    }
}

impl TryFrom<binding::FinalizeResync> for neutral::FinalizeResync {
    type Error = SdkError;
    fn try_from(value: binding::FinalizeResync) -> AdapterResult<Self> {
        Ok(Self {
            session_id: value.session_id,
        })
    }
}

impl From<neutral::ResyncPage> for binding::ResyncPage {
    fn from(value: neutral::ResyncPage) -> Self {
        match value {
            neutral::ResyncPage::Snapshot(payload) => Self::Snapshot(payload.into()),
            neutral::ResyncPage::FlushStagedKv(payload) => Self::FlushStagedKv(payload.into()),
            neutral::ResyncPage::Finalize(payload) => Self::Finalize(payload.into()),
        }
    }
}

impl TryFrom<binding::ResyncPage> for neutral::ResyncPage {
    type Error = SdkError;
    fn try_from(value: binding::ResyncPage) -> AdapterResult<Self> {
        Ok(match value {
            binding::ResyncPage::Snapshot(payload) => Self::Snapshot(payload.try_into()?),
            binding::ResyncPage::FlushStagedKv(payload) => Self::FlushStagedKv(payload.try_into()?),
            binding::ResyncPage::Finalize(payload) => Self::Finalize(payload.try_into()?),
        })
    }
}

impl From<neutral::KvSegment> for binding::KvSegment {
    fn from(value: neutral::KvSegment) -> Self {
        Self {
            operations: value.operations.into_iter().map(|value| value.into()).collect(),
        }
    }
}

impl TryFrom<binding::KvSegment> for neutral::KvSegment {
    type Error = SdkError;
    fn try_from(value: binding::KvSegment) -> AdapterResult<Self> {
        Ok(Self {
            operations: value.operations.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
        })
    }
}

impl From<neutral::FlushState> for binding::FlushState {
    fn from(value: neutral::FlushState) -> Self {
        match value {
            neutral::FlushState::More => Self::More,
            neutral::FlushState::Complete => Self::Complete,
        }
    }
}

impl TryFrom<binding::FlushState> for neutral::FlushState {
    type Error = SdkError;
    fn try_from(value: binding::FlushState) -> AdapterResult<Self> {
        Ok(match value {
            binding::FlushState::More => Self::More,
            binding::FlushState::Complete => Self::Complete,
        })
    }
}

impl From<neutral::FinalKvChoice> for binding::FinalKvChoice {
    fn from(value: neutral::FinalKvChoice) -> Self {
        match value {
            neutral::FinalKvChoice::LeaveKv => Self::LeaveKv,
            neutral::FinalKvChoice::ReplaceKvWithStagedSegments => Self::ReplaceKvWithStagedSegments,
        }
    }
}

impl TryFrom<binding::FinalKvChoice> for neutral::FinalKvChoice {
    type Error = SdkError;
    fn try_from(value: binding::FinalKvChoice) -> AdapterResult<Self> {
        Ok(match value {
            binding::FinalKvChoice::LeaveKv => Self::LeaveKv,
            binding::FinalKvChoice::ReplaceKvWithStagedSegments => Self::ReplaceKvWithStagedSegments,
        })
    }
}

impl From<neutral::SnapshotAck> for binding::SnapshotAck {
    fn from(value: neutral::SnapshotAck) -> Self {
        Self {
            session_id: value.session_id,
            page_index: value.page_index,
            kind: value.kind.into(),
            segment: value.segment.map(|value| value.into()),
        }
    }
}

impl TryFrom<binding::SnapshotAck> for neutral::SnapshotAck {
    type Error = SdkError;
    fn try_from(value: binding::SnapshotAck) -> AdapterResult<Self> {
        Ok(Self {
            session_id: value.session_id,
            page_index: value.page_index,
            kind: value.kind.try_into()?,
            segment: match value.segment { Some(value) => Some(value.try_into()?), None => None },
        })
    }
}

impl From<neutral::FlushAck> for binding::FlushAck {
    fn from(value: neutral::FlushAck) -> Self {
        Self {
            session_id: value.session_id,
            request_index: value.request_index,
            segment: value.segment.map(|value| value.into()),
            state: value.state.into(),
        }
    }
}

impl TryFrom<binding::FlushAck> for neutral::FlushAck {
    type Error = SdkError;
    fn try_from(value: binding::FlushAck) -> AdapterResult<Self> {
        Ok(Self {
            session_id: value.session_id,
            request_index: value.request_index,
            segment: match value.segment { Some(value) => Some(value.try_into()?), None => None },
            state: value.state.try_into()?,
        })
    }
}

impl From<neutral::FinalizedResync> for binding::FinalizedResync {
    fn from(value: neutral::FinalizedResync) -> Self {
        Self {
            session_id: value.session_id,
            choice: value.choice.into(),
        }
    }
}

impl TryFrom<binding::FinalizedResync> for neutral::FinalizedResync {
    type Error = SdkError;
    fn try_from(value: binding::FinalizedResync) -> AdapterResult<Self> {
        Ok(Self {
            session_id: value.session_id,
            choice: value.choice.try_into()?,
        })
    }
}

impl From<neutral::ResyncPageOutcome> for binding::ResyncPageOutcome {
    fn from(value: neutral::ResyncPageOutcome) -> Self {
        match value {
            neutral::ResyncPageOutcome::SnapshotAck(payload) => Self::SnapshotAck(payload.into()),
            neutral::ResyncPageOutcome::FlushAck(payload) => Self::FlushAck(payload.into()),
            neutral::ResyncPageOutcome::Finalized(payload) => Self::Finalized(payload.into()),
        }
    }
}

impl TryFrom<binding::ResyncPageOutcome> for neutral::ResyncPageOutcome {
    type Error = SdkError;
    fn try_from(value: binding::ResyncPageOutcome) -> AdapterResult<Self> {
        Ok(match value {
            binding::ResyncPageOutcome::SnapshotAck(payload) => Self::SnapshotAck(payload.try_into()?),
            binding::ResyncPageOutcome::FlushAck(payload) => Self::FlushAck(payload.try_into()?),
            binding::ResyncPageOutcome::Finalized(payload) => Self::Finalized(payload.try_into()?),
        })
    }
}

impl From<neutral::HttpMethod> for binding::HttpMethod {
    fn from(value: neutral::HttpMethod) -> Self {
        match value {
            neutral::HttpMethod::Get => Self::Get,
            neutral::HttpMethod::Post => Self::Post,
            neutral::HttpMethod::Put => Self::Put,
            neutral::HttpMethod::Patch => Self::Patch,
            neutral::HttpMethod::Delete => Self::Delete,
        }
    }
}

impl TryFrom<binding::HttpMethod> for neutral::HttpMethod {
    type Error = SdkError;
    fn try_from(value: binding::HttpMethod) -> AdapterResult<Self> {
        Ok(match value {
            binding::HttpMethod::Get => Self::Get,
            binding::HttpMethod::Post => Self::Post,
            binding::HttpMethod::Put => Self::Put,
            binding::HttpMethod::Patch => Self::Patch,
            binding::HttpMethod::Delete => Self::Delete,
        })
    }
}

impl From<neutral::HttpHeader> for binding::HttpHeader {
    fn from(value: neutral::HttpHeader) -> Self {
        Self {
            name: value.name,
            value: value.value,
        }
    }
}

impl TryFrom<binding::HttpHeader> for neutral::HttpHeader {
    type Error = SdkError;
    fn try_from(value: binding::HttpHeader) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name,
            value: value.value,
        })
    }
}

impl From<neutral::HttpRequest> for binding::HttpRequest {
    fn from(value: neutral::HttpRequest) -> Self {
        Self {
            method: value.method.into(),
            origin: value.origin,
            path_and_query: value.path_and_query,
            headers: value.headers.into_iter().map(|value| value.into()).collect(),
            body: value.body.into_vec(),
        }
    }
}

impl TryFrom<binding::HttpRequest> for neutral::HttpRequest {
    type Error = SdkError;
    fn try_from(value: binding::HttpRequest) -> AdapterResult<Self> {
        Ok(Self {
            method: value.method.try_into()?,
            origin: value.origin,
            path_and_query: value.path_and_query,
            headers: value.headers.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            body: neutral::ByteList::new(value.body)?,
        })
    }
}

impl From<neutral::HttpResponse> for binding::HttpResponse {
    fn from(value: neutral::HttpResponse) -> Self {
        Self {
            status: value.status,
            headers: value.headers.into_iter().map(|value| value.into()).collect(),
            body: value.body.into_vec(),
            truncated: value.truncated,
        }
    }
}

impl TryFrom<binding::HttpResponse> for neutral::HttpResponse {
    type Error = SdkError;
    fn try_from(value: binding::HttpResponse) -> AdapterResult<Self> {
        Ok(Self {
            status: value.status,
            headers: value.headers.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            body: neutral::ByteList::new(value.body)?,
            truncated: value.truncated,
        })
    }
}

impl From<neutral::HttpErrorCode> for binding::HttpErrorCode {
    fn from(value: neutral::HttpErrorCode) -> Self {
        match value {
            neutral::HttpErrorCode::InvalidRequest => Self::InvalidRequest,
            neutral::HttpErrorCode::InvalidResponse => Self::InvalidResponse,
            neutral::HttpErrorCode::PermissionDenied => Self::PermissionDenied,
            neutral::HttpErrorCode::DnsDenied => Self::DnsDenied,
            neutral::HttpErrorCode::TlsFailed => Self::TlsFailed,
            neutral::HttpErrorCode::ConnectFailed => Self::ConnectFailed,
            neutral::HttpErrorCode::Timeout => Self::Timeout,
            neutral::HttpErrorCode::DeliveryAmbiguous => Self::DeliveryAmbiguous,
            neutral::HttpErrorCode::Unavailable => Self::Unavailable,
        }
    }
}

impl TryFrom<binding::HttpErrorCode> for neutral::HttpErrorCode {
    type Error = SdkError;
    fn try_from(value: binding::HttpErrorCode) -> AdapterResult<Self> {
        Ok(match value {
            binding::HttpErrorCode::InvalidRequest => Self::InvalidRequest,
            binding::HttpErrorCode::InvalidResponse => Self::InvalidResponse,
            binding::HttpErrorCode::PermissionDenied => Self::PermissionDenied,
            binding::HttpErrorCode::DnsDenied => Self::DnsDenied,
            binding::HttpErrorCode::TlsFailed => Self::TlsFailed,
            binding::HttpErrorCode::ConnectFailed => Self::ConnectFailed,
            binding::HttpErrorCode::Timeout => Self::Timeout,
            binding::HttpErrorCode::DeliveryAmbiguous => Self::DeliveryAmbiguous,
            binding::HttpErrorCode::Unavailable => Self::Unavailable,
        })
    }
}

impl From<neutral::DeliveryState> for binding::DeliveryState {
    fn from(value: neutral::DeliveryState) -> Self {
        match value {
            neutral::DeliveryState::NotSent => Self::NotSent,
            neutral::DeliveryState::MayHaveBeenSent => Self::MayHaveBeenSent,
            neutral::DeliveryState::ResponseReceived => Self::ResponseReceived,
        }
    }
}

impl TryFrom<binding::DeliveryState> for neutral::DeliveryState {
    type Error = SdkError;
    fn try_from(value: binding::DeliveryState) -> AdapterResult<Self> {
        Ok(match value {
            binding::DeliveryState::NotSent => Self::NotSent,
            binding::DeliveryState::MayHaveBeenSent => Self::MayHaveBeenSent,
            binding::DeliveryState::ResponseReceived => Self::ResponseReceived,
        })
    }
}

impl From<neutral::HttpError> for binding::HttpError {
    fn from(value: neutral::HttpError) -> Self {
        Self {
            code: value.code.into(),
            delivery: value.delivery.into(),
            retryable: value.retryable,
            message: value.message,
        }
    }
}

impl TryFrom<binding::HttpError> for neutral::HttpError {
    type Error = SdkError;
    fn try_from(value: binding::HttpError) -> AdapterResult<Self> {
        Ok(Self {
            code: value.code.try_into()?,
            delivery: value.delivery.try_into()?,
            retryable: value.retryable,
            message: value.message,
        })
    }
}

impl From<neutral::LogField> for binding::LogField {
    fn from(value: neutral::LogField) -> Self {
        Self {
            name: value.name,
            value: value.value.into(),
        }
    }
}

impl TryFrom<binding::LogField> for neutral::LogField {
    type Error = SdkError;
    fn try_from(value: binding::LogField) -> AdapterResult<Self> {
        Ok(Self {
            name: value.name,
            value: value.value.try_into()?,
        })
    }
}

impl From<neutral::KvEntry> for binding::KvEntry {
    fn from(value: neutral::KvEntry) -> Self {
        Self {
            key: value.key,
            value: value.value.into_vec(),
        }
    }
}

impl TryFrom<binding::KvEntry> for neutral::KvEntry {
    type Error = SdkError;
    fn try_from(value: binding::KvEntry) -> AdapterResult<Self> {
        Ok(Self {
            key: value.key,
            value: neutral::ByteList::new(value.value)?,
        })
    }
}

impl From<neutral::KvPage> for binding::KvPage {
    fn from(value: neutral::KvPage) -> Self {
        Self {
            entries: value.entries.into_iter().map(|value| value.into()).collect(),
            next_cursor: value.next_cursor,
        }
    }
}

impl TryFrom<binding::KvPage> for neutral::KvPage {
    type Error = SdkError;
    fn try_from(value: binding::KvPage) -> AdapterResult<Self> {
        Ok(Self {
            entries: value.entries.into_iter().map(|value| -> AdapterResult<_> { Ok(value.try_into()?) }).collect::<AdapterResult<Vec<_>>>()?,
            next_cursor: value.next_cursor,
        })
    }
}

}
